"""
ComfyUI node registry.

Design goal:
- Always expose NODE_CLASS_MAPPINGS for tooling/CI (e.g. comfy-org/node-diff)
- Avoid import-time hard dependency on ComfyUI-only modules (folder_paths/comfy)
  by moving those imports into node.run() where needed.
"""

from __future__ import annotations

from typing import Dict, Type, Any


# --- Import node classes (should be import-safe in CI)
# IMPORTANT: Node modules should NOT import folder_paths/comfy/requests at top-level.
# Move those imports inside run().
from atlascloud_comfyui.nodes.legacy.nodes import Example as LegacyExample
from atlascloud_comfyui.nodes.auth.atlas_client_node import AtlasClientNode

from atlascloud_comfyui.nodes.video.wan26_t2v import AtlasWAN26TextToVideo
from atlascloud_comfyui.nodes.video.wan26_i2v_flash import AtlasWAN26ImageToVideoFlash
from atlascloud_comfyui.nodes.video.wan26_i2v import AtlasWAN26ImageToVideo
from atlascloud_comfyui.nodes.video.wan26_v2v import AtlasWAN26VideoToVideo
from atlascloud_comfyui.nodes.image.wan26_t2i import AtlasWAN26TextToImage
from atlascloud_comfyui.nodes.image.wan26_image_edit import AtlasWAN26ImageEdit
from atlascloud_comfyui.nodes.image.alibaba_wan_2_7_t2i import AtlasWan27TextToImage
from atlascloud_comfyui.nodes.image.alibaba_wan_2_7_edit import AtlasWan27ImageEdit
from atlascloud_comfyui.nodes.image.alibaba_wan_2_7_pro_t2i import AtlasWan27ProTextToImage
from atlascloud_comfyui.nodes.image.alibaba_wan_2_7_pro_edit import AtlasWan27ProImageEdit

from atlascloud_comfyui.nodes.video.kling_video_o3_pro_t2v import AtlasKlingVideoO3ProTextToVideo
from atlascloud_comfyui.nodes.video.kling_video_o3_pro_i2v import AtlasKlingVideoO3ProImageToVideo
from atlascloud_comfyui.nodes.video.kling_video_o3_pro_r2v import AtlasKlingVideoO3ProReferenceToVideo
from atlascloud_comfyui.nodes.video.kling_video_o3_pro_video_edit import AtlasKlingVideoO3ProVideoEdit

from atlascloud_comfyui.nodes.video.kling_video_o3_std_t2v import AtlasKlingVideoO3StdTextToVideo
from atlascloud_comfyui.nodes.video.kling_video_o3_std_i2v import AtlasKlingVideoO3StdImageToVideo
from atlascloud_comfyui.nodes.video.kling_video_o3_std_r2v import AtlasKlingVideoO3StdReferenceToVideo
from atlascloud_comfyui.nodes.video.kling_video_o3_std_video_edit import AtlasKlingVideoO3StdVideoEdit
from atlascloud_comfyui.nodes.video.wan25_t2v import AtlasWAN25TextToVideo
from atlascloud_comfyui.nodes.video.alibaba_wan_2_2_spicy_video_extend import AtlasWan22SpicyVideoExtend
from atlascloud_comfyui.nodes.video.alibaba_wan_2_2_spicy_video_extend_lora import AtlasWan22SpicyVideoExtendLora
from atlascloud_comfyui.nodes.video.alibaba_wan_2_5_video_extend import AtlasWan25VideoExtend
from atlascloud_comfyui.nodes.video.atlascloud_wan_2_2_i2v import AtlasAtlascloudWan22ImageToVideo
from atlascloud_comfyui.nodes.video.atlascloud_wan_2_2_i2v_lora import AtlasAtlascloudWan22ImageToVideoLora
from atlascloud_comfyui.nodes.deprecated.video.wan22_t2v_720p import AtlasWAN22T2V720p
from atlascloud_comfyui.nodes.deprecated.video.alibaba_wan_2_2_t2v_480p import AtlasAlibabaWan22T2V480p
from atlascloud_comfyui.nodes.deprecated.video.alibaba_wan_2_2_i2v_720p import AtlasAlibabaWan22I2V720p
from atlascloud_comfyui.nodes.deprecated.video.alibaba_wan_2_2_i2v_480p import AtlasAlibabaWan22I2V480p
from atlascloud_comfyui.nodes.video.veo31_t2v import AtlasVeo31TextToVideo
from atlascloud_comfyui.nodes.video.kling_v26_pro_t2v import AtlasKlingV26ProTextToVideo
from atlascloud_comfyui.nodes.video.kling_video_o1_t2v import AtlasKlingVideoO1TextToVideo
from atlascloud_comfyui.nodes.video.seedance_v1_pro_t2v_1080p import AtlasSeedanceV1ProT2V1080p
from atlascloud_comfyui.nodes.video.hailuo_23_t2v_pro import AtlasHailuo23T2VPro
from atlascloud_comfyui.nodes.deprecated.video.sora2_t2v_pro import AtlasSora2TextToVideoPro
from atlascloud_comfyui.nodes.video.seedance_v15_pro_t2v import AtlasSeedanceV15ProTextToVideo
from atlascloud_comfyui.nodes.video.kling_v30_pro_t2v import AtlasKlingV30ProTextToVideo
from atlascloud_comfyui.nodes.video.kling_v30_std_t2v import AtlasKlingV30StdTextToVideo
from atlascloud_comfyui.nodes.video.kling_v30_std_i2v import AtlasKlingV30StdImageToVideo
from atlascloud_comfyui.nodes.video.kling_v30_pro_i2v import AtlasKlingV30ProImageToVideo
from atlascloud_comfyui.nodes.deprecated.video.veo3_t2v import AtlasVeo3TextToVideo
from atlascloud_comfyui.nodes.deprecated.video.luma_ray2_t2v import AtlasLumaRay2TextToVideo
from atlascloud_comfyui.nodes.deprecated.video.luma_ray2_i2v import AtlasLumaRay2ImageToVideo
from atlascloud_comfyui.nodes.deprecated.video.pika_v22_t2v import AtlasPikaV22TextToVideo
from atlascloud_comfyui.nodes.deprecated.video.pixverse_v45_t2v import AtlasPixVerseV45TextToVideo
from atlascloud_comfyui.nodes.video.hailuo_02_t2v_pro import AtlasHailuo02T2VPro
from atlascloud_comfyui.nodes.deprecated.video.sora2_i2v import AtlasSora2ImageToVideo
from atlascloud_comfyui.nodes.video.kling_v25_turbo_pro_t2v import AtlasKlingV25TurboProTextToVideo
from atlascloud_comfyui.nodes.deprecated.video.hunyuan_t2v import AtlasHunyuanTextToVideo
from atlascloud_comfyui.nodes.video.vidu_q3_i2v import AtlasViduQ3ImageToVideo
from atlascloud_comfyui.nodes.deprecated.video.vidu_q3_i2v_v2 import AtlasViduQ3ImageToVideoV2
from atlascloud_comfyui.nodes.deprecated.video.vidu_q3_t2v import AtlasViduQ3TextToVideo
from atlascloud_comfyui.nodes.video.vidu_q3_pro_t2v import AtlasViduQ3ProTextToVideo
from atlascloud_comfyui.nodes.video.vidu_q3_pro_i2v import AtlasViduQ3ProImageToVideo
from atlascloud_comfyui.nodes.video.vidu_q3_turbo_t2v import AtlasViduQ3TurboTextToVideo
from atlascloud_comfyui.nodes.video.vidu_q3_turbo_i2v import AtlasViduQ3TurboImageToVideo
from atlascloud_comfyui.nodes.video.vidu_q3_turbo_start_end_to_video import AtlasViduQ3TurboStartEndToVideo
from atlascloud_comfyui.nodes.video.vidu_q3_pro_start_end_to_video import AtlasViduQ3ProStartEndToVideo
from atlascloud_comfyui.nodes.video.wan22_spicy_i2v import AtlasWan22SpicyImageToVideo
from atlascloud_comfyui.nodes.video.wan22_turbo_spicy_i2v import AtlasWan22TurboSpicyImageToVideo
from atlascloud_comfyui.nodes.video.wan22_spicy_i2v_lora import AtlasWan22SpicyImageToVideoLora
from atlascloud_comfyui.nodes.video.wan22_turbo_spicy_i2v_lora import AtlasWan22TurboSpicyImageToVideoLora
from atlascloud_comfyui.nodes.video.wan22_turbo_i2v import AtlasWan22TurboImageToVideo
from atlascloud_comfyui.nodes.deprecated.video.veo3_fast_t2v import AtlasVeo3FastTextToVideo
from atlascloud_comfyui.nodes.video.veo31_i2v import AtlasVeo31ImageToVideo
from atlascloud_comfyui.nodes.video.google_veo31_fast_t2v import AtlasVeo31FastTextToVideo
from atlascloud_comfyui.nodes.video.google_veo31_fast_i2v import AtlasVeo31FastImageToVideo
from atlascloud_comfyui.nodes.video.google_veo31_r2v import AtlasVeo31ReferenceToVideo
from atlascloud_comfyui.nodes.video.google_gemini_omni_flash_t2v_dev import AtlasGeminiOmniFlashTextToVideoDev
from atlascloud_comfyui.nodes.video.google_gemini_omni_flash_i2v_dev import AtlasGeminiOmniFlashImageToVideoDev
from atlascloud_comfyui.nodes.video.google_gemini_omni_flash_r2v_dev import AtlasGeminiOmniFlashReferenceToVideoDev
from atlascloud_comfyui.nodes.video.google_gemini_omni_flash_t2v import AtlasGeminiOmniFlashTextToVideo
from atlascloud_comfyui.nodes.video.google_gemini_omni_flash_i2v import AtlasGeminiOmniFlashImageToVideo
from atlascloud_comfyui.nodes.video.google_gemini_omni_flash_r2v import AtlasGeminiOmniFlashReferenceToVideo
from atlascloud_comfyui.nodes.video.google_gemini_omni_flash_video_edit import AtlasGeminiOmniFlashVideoEdit
from atlascloud_comfyui.nodes.video.xai_grok_imagine_video_t2v import AtlasGrokImagineVideoTextToVideo
from atlascloud_comfyui.nodes.video.xai_grok_imagine_video_i2v import AtlasGrokImagineVideoImageToVideo
from atlascloud_comfyui.nodes.video.xai_grok_imagine_video_v15_i2v import AtlasGrokImagineVideoV15ImageToVideo
from atlascloud_comfyui.nodes.video.xai_grok_imagine_video_r2v import AtlasGrokImagineVideoReferenceToVideo
from atlascloud_comfyui.nodes.image.flux2_pro_t2i import AtlasFlux2ProTextToImage
from atlascloud_comfyui.nodes.image.flux2_flex_edit import AtlasFlux2FlexEdit
from atlascloud_comfyui.nodes.image.flux2_pro_edit import AtlasFlux2ProEdit
from atlascloud_comfyui.nodes.video.xai_grok_imagine_video_edit_video import AtlasGrokImagineVideoEdit
from atlascloud_comfyui.nodes.video.xai_grok_imagine_video_extend_video import AtlasGrokImagineVideoExtend
from atlascloud_comfyui.nodes.deprecated.video.veo3_i2v import AtlasVeo3ImageToVideo
from atlascloud_comfyui.nodes.deprecated.video.veo2_t2v import AtlasVeo2TextToVideo
from atlascloud_comfyui.nodes.deprecated.video.veo2_i2v import AtlasVeo2ImageToVideo
from atlascloud_comfyui.nodes.deprecated.video.luma_ray2_flash_t2v import AtlasLumaRay2FlashTextToVideo
from atlascloud_comfyui.nodes.deprecated.video.pika_v20_turbo_t2v import AtlasPikaV20TurboTextToVideo
from atlascloud_comfyui.nodes.deprecated.video.pika_v21_i2v import AtlasPikaV21ImageToVideo
from atlascloud_comfyui.nodes.deprecated.video.pixverse_v45_i2v import AtlasPixVerseV45ImageToVideo
from atlascloud_comfyui.nodes.video.hailuo_02_i2v_pro import AtlasHailuo02I2VPro
from atlascloud_comfyui.nodes.video.minimax_hailuo_02_i2v_standard import AtlasMinimaxHailuo02I2VStandard
from atlascloud_comfyui.nodes.video.hailuo_02_i2v_standard import AtlasHailuo02I2VStandard
from atlascloud_comfyui.nodes.deprecated.video.sora2_i2v_pro import AtlasSora2ImageToVideoPro
from atlascloud_comfyui.nodes.deprecated.video.sora2_t2v import AtlasSora2TextToVideo
from atlascloud_comfyui.nodes.video.kling_v25_turbo_pro_i2v import AtlasKlingV25TurboProImageToVideo
from atlascloud_comfyui.nodes.deprecated.video.hunyuan_i2v import AtlasHunyuanImageToVideo
from atlascloud_comfyui.nodes.video.wan25_i2v import AtlasWAN25ImageToVideo

from atlascloud_comfyui.nodes.video.kling_v26_pro_avatar import AtlasKlingV26ProAvatar
from atlascloud_comfyui.nodes.video.kling_v26_std_avatar import AtlasKlingV26StdAvatar
from atlascloud_comfyui.nodes.video.kling_v26_pro_motion_control import AtlasKlingV26ProMotionControl
from atlascloud_comfyui.nodes.video.kling_v26_std_motion_control import AtlasKlingV26StdMotionControl
from atlascloud_comfyui.nodes.video.seedance_v15_pro_i2v import AtlasSeedanceV15ProImageToVideo
from atlascloud_comfyui.nodes.video.seedance_v15_pro_i2v_spicy import AtlasSeedanceV15ProImageToVideoSpicy
from atlascloud_comfyui.nodes.video.seedance_v15_pro_i2v_fast import AtlasSeedanceV15ProImageToVideoFast
from atlascloud_comfyui.nodes.video.seedance_v15_pro_t2v_fast import AtlasSeedanceV15ProTextToVideoFast
from atlascloud_comfyui.nodes.video.kling_video_o1_i2v import AtlasKlingVideoO1ImageToVideo
from atlascloud_comfyui.nodes.video.kling_v26_pro_i2v import AtlasKlingV26ProImageToVideo

from atlascloud_comfyui.nodes.image.seedream_v45_t2i import AtlasSeedreamV45TextToImage
from atlascloud_comfyui.nodes.image.seedream_v45_edit import AtlasSeedreamV45Edit
from atlascloud_comfyui.nodes.image.seedream_v45_sequential_t2i import AtlasSeedreamV45SequentialTextToImage
from atlascloud_comfyui.nodes.image.seedream_v45_edit_sequential import AtlasSeedreamV45EditSequential
from atlascloud_comfyui.nodes.image.seedream_v4_t2i import AtlasSeedreamV4TextToImage
from atlascloud_comfyui.nodes.image.seedream_v4_sequential_t2i import AtlasSeedreamV4SequentialTextToImage
from atlascloud_comfyui.nodes.image.seedream_v4_edit import AtlasSeedreamV4Edit
from atlascloud_comfyui.nodes.image.seedream_v4_edit_sequential import AtlasSeedreamV4EditSequential
from atlascloud_comfyui.nodes.deprecated.image.zimage_turbo_lora_t2i import AtlasZImageTurboLoraTextToImage
from atlascloud_comfyui.nodes.image.zimage_turbo_t2i import AtlasZImageTurboTextToImage
from atlascloud_comfyui.nodes.image.qwen_image_edit import AtlasQwenImageEdit
from atlascloud_comfyui.nodes.image.qwen_image_edit_alibaba import AtlasAlibabaQwenImageEdit
from atlascloud_comfyui.nodes.image.qwen_image_edit_plus_alibaba import AtlasAlibabaQwenImageEditPlus
from atlascloud_comfyui.nodes.image.qwen_image_t2i_atlascloud import AtlasAtlascloudQwenImageTextToImage
from atlascloud_comfyui.nodes.image.nano_banana_pro_t2i_ultra import AtlasNanoBananaProTextToImageUltra
from atlascloud_comfyui.nodes.image.nano_banana_pro_t2i import AtlasNanoBananaProTextToImage
from atlascloud_comfyui.nodes.image.nano_banana_pro_edit import AtlasNanoBananaProEdit
from atlascloud_comfyui.nodes.image.nano_banana_pro_edit_ultra import AtlasNanoBananaProEditUltra
from atlascloud_comfyui.nodes.deprecated.image.flux2_flex_t2i import AtlasFlux2FlexTextToImage
from atlascloud_comfyui.nodes.image.flux_dev_t2i import AtlasFluxDevTextToImage
from atlascloud_comfyui.nodes.image.flux_dev_lora_t2i import AtlasFluxDevLoraTextToImage
from atlascloud_comfyui.nodes.image.krea_2_turbo_t2i import AtlasKrea2TurboTextToImage
from atlascloud_comfyui.nodes.image.nano_banana2_t2i import AtlasNanoBanana2TextToImage
from atlascloud_comfyui.nodes.deprecated.image.nano_banana2_t2i_dev import AtlasNanoBanana2TextToImageDev
from atlascloud_comfyui.nodes.image.nano_banana2_edit import AtlasNanoBanana2Edit
from atlascloud_comfyui.nodes.image.nano_banana2_r2i import AtlasNanoBanana2ReferenceToImage
from atlascloud_comfyui.nodes.image.nano_banana2_r2i_dev import AtlasNanoBanana2ReferenceToImageDev
from atlascloud_comfyui.nodes.deprecated.image.nano_banana2_edit_dev import AtlasNanoBanana2EditDev
from atlascloud_comfyui.nodes.image.nano_banana2_lite_t2i import AtlasNanoBanana2LiteTextToImage
from atlascloud_comfyui.nodes.image.nano_banana2_lite_t2i_dev import AtlasNanoBanana2LiteTextToImageDev
from atlascloud_comfyui.nodes.image.nano_banana2_lite_edit import AtlasNanoBanana2LiteEdit
from atlascloud_comfyui.nodes.image.nano_banana2_lite_edit_dev import AtlasNanoBanana2LiteEditDev
from atlascloud_comfyui.nodes.image.nano_banana2_lite_r2i import AtlasNanoBanana2LiteReferenceToImage
from atlascloud_comfyui.nodes.image.hidream_o1_15_t2i import AtlasHiDreamO115TextToImage
from atlascloud_comfyui.nodes.image.hidream_o1_15_edit import AtlasHiDreamO115Edit
from atlascloud_comfyui.nodes.image.reve_21_t2i import AtlasReve21TextToImage
from atlascloud_comfyui.nodes.image.reve_21_edit import AtlasReve21Edit
from atlascloud_comfyui.nodes.image.reve_21_remix import AtlasReve21Remix
from atlascloud_comfyui.nodes.video.sync_lipsync_v3 import AtlasSyncLipsyncV3
from atlascloud_comfyui.nodes.video.veed_lipsync import AtlasVeedLipsync
from atlascloud_comfyui.nodes.image.seedream_v50_lite_t2i import AtlasSeedreamV50LiteTextToImage
from atlascloud_comfyui.nodes.image.seedream_v50_lite_edit import AtlasSeedreamV50LiteEdit
from atlascloud_comfyui.nodes.image.seedream_v50_lite_sequential_t2i import AtlasSeedreamV50LiteSequentialTextToImage
from atlascloud_comfyui.nodes.image.seedream_v50_lite_edit_sequential import AtlasSeedreamV50LiteEditSequential
from atlascloud_comfyui.nodes.image.imagen4_t2i import AtlasImagen4TextToImage
from atlascloud_comfyui.nodes.image.imagen4_fast_t2i import AtlasImagen4FastTextToImage
from atlascloud_comfyui.nodes.image.imagen4_ultra_t2i import AtlasImagen4UltraTextToImage
from atlascloud_comfyui.nodes.image.imagen3_t2i import AtlasImagen3TextToImage
from atlascloud_comfyui.nodes.image.imagen3_fast_t2i import AtlasImagen3FastTextToImage
from atlascloud_comfyui.nodes.image.wan25_t2i import AtlasWan25TextToImage
from atlascloud_comfyui.nodes.image.baidu_ernie_image_turbo_t2i import AtlasBaiduERNIEImageTurboTextToImage
from atlascloud_comfyui.nodes.image.wan25_image_edit import AtlasWan25ImageEdit
from atlascloud_comfyui.nodes.image.nano_banana_t2i import AtlasNanoBananaTextToImage
from atlascloud_comfyui.nodes.deprecated.image.nano_banana_t2i_dev import AtlasNanoBananaTextToImageDeveloper
from atlascloud_comfyui.nodes.image.nano_banana_edit import AtlasNanoBananaEdit
from atlascloud_comfyui.nodes.deprecated.image.nano_banana_edit_dev import AtlasNanoBananaEditDeveloper
from atlascloud_comfyui.nodes.deprecated.image.nano_banana_pro_t2i_dev import AtlasNanoBananaProTextToImageDeveloper
from atlascloud_comfyui.nodes.deprecated.image.nano_banana_pro_edit_dev import AtlasNanoBananaProEditDeveloper
from atlascloud_comfyui.nodes.image.flux_kontext_dev_edit import AtlasFluxKontextDevEdit
from atlascloud_comfyui.nodes.image.flux_kontext_dev_lora_edit import AtlasFluxKontextDevLoraEdit
from atlascloud_comfyui.nodes.image.flux_schnell_t2i import AtlasFluxSchnellTextToImage
from atlascloud_comfyui.nodes.deprecated.image.ideogram_v3_quality_t2i import AtlasIdeogramV3QualityTextToImage
from atlascloud_comfyui.nodes.deprecated.image.ideogram_v3_turbo_t2i import AtlasIdeogramV3TurboTextToImage
from atlascloud_comfyui.nodes.deprecated.image.luma_photon_t2i import AtlasLumaPhotonTextToImage
from atlascloud_comfyui.nodes.deprecated.image.luma_photon_flash_t2i import AtlasLumaPhotonFlashTextToImage
from atlascloud_comfyui.nodes.deprecated.image.recraft_v3_t2i import AtlasRecraftV3TextToImage
from atlascloud_comfyui.nodes.image.qwen_image_edit_plus_20251215 import AtlasQwenImageEditPlus20251215
from atlascloud_comfyui.nodes.image.qwen_image_t2i_plus import AtlasQwenImageTextToImagePlus
from atlascloud_comfyui.nodes.image.qwen_image_t2i_max import AtlasQwenImageTextToImageMax

from atlascloud_comfyui.nodes.image.openai_gpt_image_1_t2i import AtlasOpenAIGPTImage1TextToImage
from atlascloud_comfyui.nodes.image.openai_gpt_image_1_edit import AtlasOpenAIGPTImage1Edit
from atlascloud_comfyui.nodes.image.openai_gpt_image_1_mini_t2i import AtlasOpenAIGPTImage1MiniTextToImage
from atlascloud_comfyui.nodes.image.openai_gpt_image_1_mini_edit import AtlasOpenAIGPTImage1MiniEdit
from atlascloud_comfyui.nodes.image.openai_gpt_image_15_t2i import AtlasOpenAIGPTImage15TextToImage
from atlascloud_comfyui.nodes.image.openai_gpt_image_15_edit import AtlasOpenAIGPTImage15Edit
from atlascloud_comfyui.nodes.image.openai_gpt_image_2_t2i import AtlasOpenAIGPTImage2TextToImage
from atlascloud_comfyui.nodes.image.openai_gpt_image_2_edit import AtlasOpenAIGPTImage2Edit
from atlascloud_comfyui.nodes.deprecated.image.openai_gpt_image_2_dev_t2i import AtlasOpenAIGPTImage2DeveloperTextToImage
from atlascloud_comfyui.nodes.deprecated.image.openai_gpt_image_2_dev_edit import AtlasOpenAIGPTImage2DeveloperEdit
from atlascloud_comfyui.nodes.image.qwen_image_20_t2i import AtlasQwenImage20TextToImage
from atlascloud_comfyui.nodes.image.qwen_image_20_edit import AtlasQwenImage20Edit
from atlascloud_comfyui.nodes.image.qwen_image_20_pro_t2i import AtlasQwenImage20ProTextToImage
from atlascloud_comfyui.nodes.image.qwen_image_20_pro_edit import AtlasQwenImage20ProEdit

from atlascloud_comfyui.nodes.video.seedance_v1_pro_fast_t2v import AtlasSeedanceV1ProFastTextToVideo
from atlascloud_comfyui.nodes.video.seedance_v1_pro_fast_i2v import AtlasSeedanceV1ProFastImageToVideo
from atlascloud_comfyui.nodes.video.wan25_fast_t2v import AtlasWAN25TextToVideoFast
from atlascloud_comfyui.nodes.video.wan25_fast_i2v import AtlasWAN25ImageToVideoFast
from atlascloud_comfyui.nodes.video.wan22_animate_mix import AtlasWan22AnimateMix
from atlascloud_comfyui.nodes.video.wan22_animate_move import AtlasWan22AnimateMove
from atlascloud_comfyui.nodes.video.atlascloud_wan_2_2_turbo_infinite_i2v import (
    AtlasWan22TurboInfiniteImageToVideo,
)
from atlascloud_comfyui.nodes.video.atlascloud_wan_2_2_turbo_infinite_i2v_lora import (
    AtlasWan22TurboInfiniteImageToVideoLoRA,
)
from atlascloud_comfyui.nodes.video.atlascloud_wan_2_2_turbo_spicy_infinite_i2v import (
    AtlasWan22TurboSpicyInfiniteImageToVideo,
)
from atlascloud_comfyui.nodes.video.atlascloud_wan_2_2_turbo_spicy_infinite_i2v_lora import (
    AtlasWan22TurboSpicyInfiniteImageToVideoLoRA,
)
from atlascloud_comfyui.nodes.video.atlascloud_wan_2_6_spicy_i2v import AtlasWan26SpicyImageToVideo
from atlascloud_comfyui.nodes.video.atlascloud_wan_2_7_spicy_i2v import AtlasWan27SpicyImageToVideo
from atlascloud_comfyui.nodes.video.van25_t2v import AtlasAtlascloudVan25TextToVideo
from atlascloud_comfyui.nodes.video.van25_i2v import AtlasAtlascloudVan25ImageToVideo
from atlascloud_comfyui.nodes.video.van26_t2v import AtlasVan26TextToVideo
from atlascloud_comfyui.nodes.video.van26_i2v import AtlasVan26ImageToVideo
from atlascloud_comfyui.nodes.video.atlascloud_infinitetalk_a2v import AtlasInfiniteTalkAudioToVideo
from atlascloud_comfyui.nodes.video.vidu_reference_to_video_q1 import AtlasViduReferenceToVideoQ1
from atlascloud_comfyui.nodes.video.vidu_reference_to_video_v2 import AtlasViduReferenceToVideoV2
from atlascloud_comfyui.nodes.video.vidu_start_end_to_video_v2 import AtlasViduStartEndToVideoV2
from atlascloud_comfyui.nodes.deprecated.video.vidu_q2_pro_fast_reference_to_video import AtlasViduQ2ProFastReferenceToVideo
from atlascloud_comfyui.nodes.deprecated.video.vidu_q2_pro_fast_reference_to_video_with_audio import (
    AtlasViduQ2ProFastReferenceToVideoWithAudio,
)
from atlascloud_comfyui.nodes.video.kling_v20_i2v_master import AtlasKlingV20I2VMaster
from atlascloud_comfyui.nodes.deprecated.video.veo3_fast_i2v import AtlasVeo3FastImageToVideo
from atlascloud_comfyui.nodes.video.kling_v21_t2v_master import AtlasKlingV21T2VMaster
from atlascloud_comfyui.nodes.video.kling_v21_i2v_master import AtlasKlingV21I2VMaster
from atlascloud_comfyui.nodes.video.kling_v21_i2v_pro_start_end_frame import AtlasKlingV21I2VProStartEndFrame
from atlascloud_comfyui.nodes.video.kwaivgi_kling_v2_1_i2v_pro import AtlasKwaivgiKlingV21I2VPro
from atlascloud_comfyui.nodes.video.kwaivgi_kling_v2_1_i2v_standard import AtlasKwaivgiKlingV21I2VStandard

from atlascloud_comfyui.nodes.video.atlascloud_video_upscaler_v2v import AtlasVideoUpscalerVideoToVideo
from atlascloud_comfyui.nodes.video.veed_fabric_10_fast_i2v import AtlasVeedFabric10FastImageToVideo
from atlascloud_comfyui.nodes.video.veed_fabric_10_i2v import AtlasVeedFabric10ImageToVideo
from atlascloud_comfyui.nodes.image.xai_grok_imagine_image_quality_t2i import AtlasGrokImagineImageQualityTextToImage
from atlascloud_comfyui.nodes.image.xai_grok_imagine_image_quality_edit import AtlasGrokImagineImageQualityEdit
from atlascloud_comfyui.nodes.image.xai_grok_imagine_image_t2i import AtlasGrokImagineImageTextToImage
from atlascloud_comfyui.nodes.image.xai_grok_imagine_image_edit import AtlasGrokImagineImageEdit

from atlascloud_comfyui.nodes.image.seedream_v50_pro_t2i import AtlasSeedreamV50ProTextToImage
from atlascloud_comfyui.nodes.image.seedream_v50_pro_edit import AtlasSeedreamV50ProEdit
from atlascloud_comfyui.nodes.image.nvidia_cosmos_3_super_t2i import AtlasCosmos3SuperTextToImage
from atlascloud_comfyui.nodes.video.nvidia_cosmos_3_super_i2v import AtlasCosmos3SuperImageToVideo
from atlascloud_comfyui.nodes.image.ideogram_v4_turbo_t2i import AtlasIdeogramV4TurboTextToImage
from atlascloud_comfyui.nodes.image.ideogram_v4_quality_t2i import AtlasIdeogramV4QualityTextToImage

from atlascloud_comfyui.nodes.video.ltx_2_3_quality_t2v import AtlasLtx23QualityTextToVideo
from atlascloud_comfyui.nodes.video.ltx_2_3_quality_i2v import AtlasLtx23QualityImageToVideo
from atlascloud_comfyui.nodes.video.ltx_2_3_quality_extend_video import AtlasLtx23QualityExtendVideo

from atlascloud_comfyui.nodes.video.kling_v16_multi_i2v_pro import AtlasKlingV16MultiI2VPro
from atlascloud_comfyui.nodes.video.kling_v16_multi_i2v_standard import AtlasKlingV16MultiI2VStandard
from atlascloud_comfyui.nodes.video.kling_v16_i2v_standard import AtlasKlingV16I2VStandard
from atlascloud_comfyui.nodes.video.kling_effects import AtlasKlingEffects
from atlascloud_comfyui.nodes.video.kwaivgi_kling_v1_6_t2v_standard import AtlasKwaivgiKlingV16T2VStandard
from atlascloud_comfyui.nodes.video.kwaivgi_kling_v1_6_i2v_pro import AtlasKwaivgiKlingV16I2VPro

from atlascloud_comfyui.nodes.video.hailuo_23_t2v_standard import AtlasHailuo23T2VStandard
from atlascloud_comfyui.nodes.video.hailuo_23_i2v_standard import AtlasHailuo23I2VStandard
from atlascloud_comfyui.nodes.video.hailuo_23_i2v_pro import AtlasHailuo23I2VPro
from atlascloud_comfyui.nodes.video.hailuo_23_fast import AtlasHailuo23Fast
from atlascloud_comfyui.nodes.video.hailuo_02_fast import AtlasHailuo02Fast
from atlascloud_comfyui.nodes.video.hailuo_02_pro import AtlasHailuo02Pro
from atlascloud_comfyui.nodes.video.hailuo_02_t2v_standard import AtlasHailuo02T2VStandard

from atlascloud_comfyui.nodes.deprecated.video.seedance_v1_lite_t2v_1080p import AtlasSeedanceV1LiteT2V1080p
from atlascloud_comfyui.nodes.deprecated.video.seedance_v1_lite_t2v_720p import AtlasSeedanceV1LiteT2V720p
from atlascloud_comfyui.nodes.deprecated.video.seedance_v1_lite_i2v_1080p import AtlasSeedanceV1LiteI2V1080p
from atlascloud_comfyui.nodes.video.bytedance_seedance_2_0_t2v import AtlasSeedance20TextToVideo
from atlascloud_comfyui.nodes.video.bytedance_seedance_2_0_i2v import AtlasSeedance20ImageToVideo
from atlascloud_comfyui.nodes.video.bytedance_seedance_2_0_r2v import AtlasSeedance20ReferenceToVideo
from atlascloud_comfyui.nodes.video.bytedance_seedance_2_5_r2v import AtlasSeedance25ReferenceToVideo
from atlascloud_comfyui.nodes.video.bytedance_seedance_2_5_t2v import AtlasSeedance25TextToVideo
from atlascloud_comfyui.nodes.video.bytedance_seedance_2_5_i2v import AtlasSeedance25ImageToVideo
from atlascloud_comfyui.nodes.video.bytedance_seedance_2_5_r2v_multi import AtlasSeedance25ReferenceToVideoMulti
from atlascloud_comfyui.nodes.video.bytedance_seedance_2_0_fast_t2v import AtlasSeedance20FastTextToVideo
from atlascloud_comfyui.nodes.video.bytedance_seedance_2_0_fast_i2v import AtlasSeedance20FastImageToVideo
from atlascloud_comfyui.nodes.video.bytedance_seedance_2_0_fast_r2v import AtlasSeedance20FastReferenceToVideo
from atlascloud_comfyui.nodes.video.bytedance_seedance_2_0_mini_t2v import AtlasSeedance20MiniTextToVideo
from atlascloud_comfyui.nodes.video.bytedance_seedance_2_0_mini_i2v import AtlasSeedance20MiniImageToVideo
from atlascloud_comfyui.nodes.video.bytedance_seedance_2_0_mini_r2v import AtlasSeedance20MiniReferenceToVideo
from atlascloud_comfyui.nodes.video.bytedance_avatar_omni_human_v15 import AtlasAvatarOmniHumanV15
from atlascloud_comfyui.nodes.image.atlascloud_image_upscaler import AtlasImageUpscaler
from atlascloud_comfyui.nodes.image.atlascloud_face_swap_image import AtlasFaceSwapImage
from atlascloud_comfyui.nodes.image.atlascloud_photo_cleanup import AtlasPhotoCleanup
from atlascloud_comfyui.nodes.video.atlascloud_face_swap_video import AtlasFaceSwapVideo
from atlascloud_comfyui.nodes.deprecated.video.bytedance_seedance_2_0_t2v_upscaled import AtlasSeedance20TextToVideoUpscaled
from atlascloud_comfyui.nodes.deprecated.video.bytedance_seedance_2_0_i2v_upscaled import AtlasSeedance20ImageToVideoUpscaled
from atlascloud_comfyui.nodes.deprecated.video.bytedance_seedance_2_0_r2v_upscaled import AtlasSeedance20ReferenceToVideoUpscaled
from atlascloud_comfyui.nodes.deprecated.video.bytedance_seedance_2_0_fast_t2v_upscaled import AtlasSeedance20FastTextToVideoUpscaled
from atlascloud_comfyui.nodes.deprecated.video.bytedance_seedance_2_0_fast_i2v_upscaled import AtlasSeedance20FastImageToVideoUpscaled
from atlascloud_comfyui.nodes.deprecated.video.bytedance_seedance_2_0_fast_r2v_upscaled import AtlasSeedance20FastReferenceToVideoUpscaled
from atlascloud_comfyui.nodes.video.alibaba_wan_2_7_t2v import AtlasWan27TextToVideo
from atlascloud_comfyui.nodes.video.alibaba_wan_2_7_i2v import AtlasWan27ImageToVideo
from atlascloud_comfyui.nodes.video.alibaba_wan_2_7_r2v import AtlasWan27ReferenceToVideo
from atlascloud_comfyui.nodes.video.alibaba_wan_2_7_video_edit import AtlasWan27VideoEdit
from atlascloud_comfyui.nodes.video.alibaba_happyhorse_1_0_t2v import AtlasHappyHorse10TextToVideo
from atlascloud_comfyui.nodes.video.alibaba_happyhorse_1_0_i2v import AtlasHappyHorse10ImageToVideo
from atlascloud_comfyui.nodes.video.alibaba_happyhorse_1_0_r2v import AtlasHappyHorse10ReferenceToVideo
from atlascloud_comfyui.nodes.video.alibaba_happyhorse_1_0_video_edit import AtlasHappyHorse10VideoEdit
from atlascloud_comfyui.nodes.video.alibaba_happyhorse_1_1_t2v import AtlasHappyHorse11TextToVideo
from atlascloud_comfyui.nodes.video.alibaba_happyhorse_1_1_i2v import AtlasHappyHorse11ImageToVideo
from atlascloud_comfyui.nodes.video.alibaba_happyhorse_1_1_r2v import AtlasHappyHorse11ReferenceToVideo
from atlascloud_comfyui.nodes.video.google_veo31_lite_t2v import AtlasVeo31LiteTextToVideo
from atlascloud_comfyui.nodes.video.google_veo31_lite_i2v import AtlasVeo31LiteImageToVideo
from atlascloud_comfyui.nodes.video.google_veo31_lite_start_end_frame_t2v import AtlasVeo31LiteStartEndFrameToVideo
from atlascloud_comfyui.nodes.video.vidu_q3_r2v import AtlasViduQ3ReferenceToVideo
from atlascloud_comfyui.nodes.video.vidu_q3_mix_r2v import AtlasViduQ3MixReferenceToVideo

from atlascloud_comfyui.nodes.video.pixverse_c1_t2v import AtlasPixVerseC1TextToVideo
from atlascloud_comfyui.nodes.video.pixverse_c1_i2v import AtlasPixVerseC1ImageToVideo
from atlascloud_comfyui.nodes.video.pixverse_c1_r2v import AtlasPixVerseC1ReferenceToVideo
from atlascloud_comfyui.nodes.video.pixverse_v6_t2v import AtlasPixVerseV6TextToVideo
from atlascloud_comfyui.nodes.video.pixverse_v6_i2v import AtlasPixVerseV6ImageToVideo
from atlascloud_comfyui.nodes.video.pixverse_v6_r2v import AtlasPixVerseV6ReferenceToVideo
from atlascloud_comfyui.nodes.video.pixverse_v6_video_extend import AtlasPixVerseV6VideoExtend
from atlascloud_comfyui.nodes.video.pixverse_c1_start_end import AtlasPixVerseC1StartEndToVideo
from atlascloud_comfyui.nodes.video.pixverse_v6_start_end import AtlasPixVerseV6StartEndToVideo
from atlascloud_comfyui.nodes.video.midjourney_v81_i2v import AtlasMidjourneyV81ImageToVideo
from atlascloud_comfyui.nodes.image.midjourney_v81_t2i import AtlasMidjourneyV81TextToImage
from atlascloud_comfyui.nodes.image.midjourney_v81_i2i import AtlasMidjourneyV81ImageToImage
from atlascloud_comfyui.nodes.image.midjourney_v81_blend import AtlasMidjourneyV81Blend
from atlascloud_comfyui.nodes.image.midjourney_v81_remove_bg import AtlasMidjourneyV81RemoveBackground
from atlascloud_comfyui.nodes.image.midjourney_v81_style_transfer import AtlasMidjourneyV81StyleTransfer
from atlascloud_comfyui.nodes.video.youchuan_v81_i2v import AtlasYouchuanV81ImageToVideo
from atlascloud_comfyui.nodes.image.youchuan_v81_t2i import AtlasYouchuanV81TextToImage
from atlascloud_comfyui.nodes.image.youchuan_v81_i2i import AtlasYouchuanV81ImageToImage
from atlascloud_comfyui.nodes.image.youchuan_v81_blend import AtlasYouchuanV81Blend
from atlascloud_comfyui.nodes.image.youchuan_v81_remove_bg import AtlasYouchuanV81RemoveBackground
from atlascloud_comfyui.nodes.image.youchuan_v81_style_transfer import AtlasYouchuanV81StyleTransfer
from atlascloud_comfyui.nodes.video.kling_v30_4k_i2v import AtlasKlingV304KImageToVideo
from atlascloud_comfyui.nodes.video.kling_v30_4k_t2v import AtlasKlingV304KTextToVideo
from atlascloud_comfyui.nodes.video.kling_video_o3_4k_i2v import AtlasKlingVideoO34KImageToVideo
from atlascloud_comfyui.nodes.video.kling_video_o3_4k_t2v import AtlasKlingVideoO34KTextToVideo
from atlascloud_comfyui.nodes.video.kling_v30_turbo_i2v import AtlasKlingV30TurboImageToVideo
from atlascloud_comfyui.nodes.video.kling_v30_turbo_t2v import AtlasKlingV30TurboTextToVideo
from atlascloud_comfyui.nodes.image.mai_image_25_t2i import AtlasMAIImage25TextToImage
from atlascloud_comfyui.nodes.image.mai_image_25_flash_t2i import AtlasMAIImage25FlashTextToImage
from atlascloud_comfyui.nodes.image.mai_image_25_edit import AtlasMAIImage25Edit
from atlascloud_comfyui.nodes.image.mai_image_25_flash_edit import AtlasMAIImage25FlashEdit
from atlascloud_comfyui.nodes.video.vidu_q1_t2v import AtlasViduQ1TextToVideo
from atlascloud_comfyui.nodes.video.vidu_q1_i2v import AtlasViduQ1ImageToVideo
from atlascloud_comfyui.nodes.video.vidu_q1_start_end import AtlasViduQ1StartEndToVideo
from atlascloud_comfyui.nodes.video.vidu_q1_r2v import AtlasViduQ1ReferenceToVideo
from atlascloud_comfyui.nodes.video.vidu_q2_t2v import AtlasViduQ2TextToVideo
from atlascloud_comfyui.nodes.video.vidu_q2_r2v import AtlasViduQ2ReferenceToVideo
from atlascloud_comfyui.nodes.video.vidu_q2_pro_i2v import AtlasViduQ2ProImageToVideo
from atlascloud_comfyui.nodes.video.vidu_q2_pro_start_end import AtlasViduQ2ProStartEndToVideo
from atlascloud_comfyui.nodes.video.vidu_q2_pro_r2v import AtlasViduQ2ProReferenceToVideo
from atlascloud_comfyui.nodes.video.vidu_q2_pro_fast_i2v import AtlasViduQ2ProFastImageToVideo
from atlascloud_comfyui.nodes.video.vidu_q2_pro_fast_start_end import AtlasViduQ2ProFastStartEndToVideo
from atlascloud_comfyui.nodes.video.vidu_q2_turbo_i2v import AtlasViduQ2TurboImageToVideo
from atlascloud_comfyui.nodes.video.vidu_q2_turbo_start_end import AtlasViduQ2TurboStartEndToVideo

from atlascloud_comfyui.nodes.deprecated.video.bytedance_seedance_v1_lite_t2v_480p import AtlasBytedanceSeedanceV1LiteT2V480p
from atlascloud_comfyui.nodes.deprecated.video.bytedance_seedance_v1_lite_i2v_720p import AtlasBytedanceSeedanceV1LiteI2V720p
from atlascloud_comfyui.nodes.deprecated.video.bytedance_seedance_v1_lite_i2v_480p import AtlasBytedanceSeedanceV1LiteI2V480p
from atlascloud_comfyui.nodes.video.bytedance_seedance_v1_pro_t2v_720p import AtlasBytedanceSeedanceV1ProT2V720p
from atlascloud_comfyui.nodes.video.bytedance_seedance_v1_pro_t2v_480p import AtlasBytedanceSeedanceV1ProT2V480p
from atlascloud_comfyui.nodes.video.bytedance_seedance_v1_pro_i2v_1080p import AtlasBytedanceSeedanceV1ProI2V1080p
from atlascloud_comfyui.nodes.video.bytedance_seedance_v1_pro_i2v_720p import AtlasBytedanceSeedanceV1ProI2V720p
from atlascloud_comfyui.nodes.video.bytedance_seedance_v1_pro_i2v_480p import AtlasBytedanceSeedanceV1ProI2V480p

from atlascloud_comfyui.nodes.video.kling_v20_t2v_master import AtlasKlingV20T2VMaster

from atlascloud_comfyui.nodes.utils.image_preview import AtlasImagePreviewURL
from atlascloud_comfyui.nodes.utils.video_previewer import AtlasVideoPreviewer
from atlascloud_comfyui.nodes.utils.image_to_base64 import AtlasImageToBase64
from atlascloud_comfyui.nodes.utils.multi_image_to_base64 import AtlasMultiImageToBase64
from atlascloud_comfyui.nodes.utils.upload_videos_to_asset import AtlasUploadVideosToAsset
from atlascloud_comfyui.nodes.utils.upload_audio_to_asset import AtlasUploadAudioToAsset
from atlascloud_comfyui.nodes.utils.upload_audios_to_asset import AtlasUploadAudiosToAsset
from atlascloud_comfyui.nodes.utils.multi_image_to_seedance_assets import AtlasMultiImageToSeedanceAssets


NODE_CLASS_MAPPINGS: Dict[str, Type[Any]] = {
    "AtlasCloud Client": AtlasClientNode,
    "AtlasCloud WAN2.5 Text-to-Video": AtlasWAN25TextToVideo,
    "AtlasCloud WAN2.6 Text-to-Video": AtlasWAN26TextToVideo,
    "AtlasCloud WAN2.6 Text-to-Image": AtlasWAN26TextToImage,
    "AtlasCloud WAN2.7 Text-to-Image": AtlasWan27TextToImage,
    "AtlasCloud WAN2.7 Image-Edit": AtlasWan27ImageEdit,
    "AtlasCloud WAN2.7 Pro Text-to-Image": AtlasWan27ProTextToImage,
    "AtlasCloud WAN2.7 Pro Image-Edit": AtlasWan27ProImageEdit,
    "AtlasCloud WAN2.5 Text-to-Image": AtlasWan25TextToImage,
    "AtlasCloud Baidu ERNIE-Image-Turbo Text-to-Image": AtlasBaiduERNIEImageTurboTextToImage,
    "AtlasCloud MAI-Image-2.5 Text-to-Image": AtlasMAIImage25TextToImage,
    "AtlasCloud MAI-Image-2.5-Flash Text-to-Image": AtlasMAIImage25FlashTextToImage,
    "AtlasCloud MAI-Image-2.5 Edit": AtlasMAIImage25Edit,
    "AtlasCloud MAI-Image-2.5-Flash Edit": AtlasMAIImage25FlashEdit,
    "AtlasCloud WAN2.5 Image-Edit": AtlasWan25ImageEdit,
    "AtlasCloud WAN2.6 Image-Edit": AtlasWAN26ImageEdit,
    "AtlasCloud WAN2.6 Image-to-Video": AtlasWAN26ImageToVideo,
    "AtlasCloud WAN2.6 Image-to-Video Flash": AtlasWAN26ImageToVideoFlash,
    "AtlasCloud WAN2.6 Video-to-Video": AtlasWAN26VideoToVideo,
    "AtlasCloud WAN2.2 Spicy Video Extend": AtlasWan22SpicyVideoExtend,
    "AtlasCloud WAN2.2 Spicy Video Extend LoRA": AtlasWan22SpicyVideoExtendLora,
    "AtlasCloud WAN2.5 Video Extend": AtlasWan25VideoExtend,
    "AtlasCloud WAN2.2 (AtlasCloud) Image-to-Video": AtlasAtlascloudWan22ImageToVideo,
    "AtlasCloud WAN2.2 (AtlasCloud) Image-to-Video LoRA": AtlasAtlascloudWan22ImageToVideoLora,
    "AtlasCloud Kling Video O3 Pro Text-to-Video": AtlasKlingVideoO3ProTextToVideo,
    "AtlasCloud Kling Video O3 Pro Image-to-Video": AtlasKlingVideoO3ProImageToVideo,
    "AtlasCloud Kling Video O3 Pro Reference-to-Video": AtlasKlingVideoO3ProReferenceToVideo,
    "AtlasCloud Kling Video O3 Pro Video-Edit": AtlasKlingVideoO3ProVideoEdit,
    "AtlasCloud Kling Video O3 Std Text-to-Video": AtlasKlingVideoO3StdTextToVideo,
    "AtlasCloud Kling Video O3 Std Image-to-Video": AtlasKlingVideoO3StdImageToVideo,
    "AtlasCloud Kling Video O3 Std Reference-to-Video": AtlasKlingVideoO3StdReferenceToVideo,
    "AtlasCloud Kling Video O3 Std Video-Edit": AtlasKlingVideoO3StdVideoEdit,
    "AtlasCloud WAN2.2 Text-to-Video 720p": AtlasWAN22T2V720p,
    "AtlasCloud WAN2.2 Text-to-Video 480p": AtlasAlibabaWan22T2V480p,
    "AtlasCloud VEO3.1 Text-to-Video": AtlasVeo31TextToVideo,
    "AtlasCloud Kling V2.6 Pro Text-to-Video": AtlasKlingV26ProTextToVideo,
    "AtlasCloud Kling V2.6 Pro Avatar": AtlasKlingV26ProAvatar,
    "AtlasCloud Kling V2.6 Std Avatar": AtlasKlingV26StdAvatar,
    "AtlasCloud Kling V2.6 Pro Motion-Control": AtlasKlingV26ProMotionControl,
    "AtlasCloud Kling V2.6 Std Motion-Control": AtlasKlingV26StdMotionControl,
    "AtlasCloud Kling V2.6 Pro Image-to-Video": AtlasKlingV26ProImageToVideo,
    "AtlasCloud Kling Video O1 Text-to-Video": AtlasKlingVideoO1TextToVideo,
    "AtlasCloud Kling Video O1 Image-to-Video": AtlasKlingVideoO1ImageToVideo,
    "AtlasCloud Seedance V1 Pro Text-to-Video 1080p": AtlasSeedanceV1ProT2V1080p,
    "AtlasCloud Seedance V1 Pro Text-to-Video 720p": AtlasBytedanceSeedanceV1ProT2V720p,
    "AtlasCloud Seedance V1 Pro Text-to-Video 480p": AtlasBytedanceSeedanceV1ProT2V480p,
    "AtlasCloud Seedance V1 Lite Text-to-Video 480p": AtlasBytedanceSeedanceV1LiteT2V480p,
    "AtlasCloud Hailuo 2.3 Pro Text-to-Video": AtlasHailuo23T2VPro,
    "AtlasCloud Sora 2 Text-to-Video Pro": AtlasSora2TextToVideoPro,
    "AtlasCloud Seedance V1.5 Pro Text-to-Video": AtlasSeedanceV15ProTextToVideo,
    "AtlasCloud Seedance V1.5 Pro Text-to-Video Fast": AtlasSeedanceV15ProTextToVideoFast,
    "AtlasCloud Seedance 2.0 Text-to-Video": AtlasSeedance20TextToVideo,
    "AtlasCloud Seedance 2.0 Image-to-Video": AtlasSeedance20ImageToVideo,
    "AtlasCloud Seedance 2.0 Reference-to-Video": AtlasSeedance20ReferenceToVideo,
    "AtlasCloud Seedance 2.5 Text-to-Video": AtlasSeedance25TextToVideo,
    "AtlasCloud Seedance 2.5 Image-to-Video": AtlasSeedance25ImageToVideo,
    "AtlasCloud Seedance 2.5 Reference-to-Video": AtlasSeedance25ReferenceToVideo,
    "AtlasCloud Seedance 2.5 Reference-to-Video (Multi 30img/10vid)": AtlasSeedance25ReferenceToVideoMulti,
    "AtlasCloud Seedance 2.0 Fast Text-to-Video": AtlasSeedance20FastTextToVideo,
    "AtlasCloud Seedance 2.0 Fast Image-to-Video": AtlasSeedance20FastImageToVideo,
    "AtlasCloud Seedance 2.0 Fast Reference-to-Video": AtlasSeedance20FastReferenceToVideo,
    "AtlasCloud Seedance 2.0 Mini Text-to-Video": AtlasSeedance20MiniTextToVideo,
    "AtlasCloud Seedance 2.0 Mini Image-to-Video": AtlasSeedance20MiniImageToVideo,
    "AtlasCloud Seedance 2.0 Mini Reference-to-Video": AtlasSeedance20MiniReferenceToVideo,
    "AtlasCloud Avatar Omni Human 1.5": AtlasAvatarOmniHumanV15,
    "AtlasCloud Image Upscaler": AtlasImageUpscaler,
    "AtlasCloud Face Swap (Image)": AtlasFaceSwapImage,
    "AtlasCloud Photo Cleanup": AtlasPhotoCleanup,
    "AtlasCloud Face Swap (Video)": AtlasFaceSwapVideo,
    "AtlasCloud Seedance 2.0 Text-to-Video Upscaled": AtlasSeedance20TextToVideoUpscaled,
    "AtlasCloud Seedance 2.0 Image-to-Video Upscaled": AtlasSeedance20ImageToVideoUpscaled,
    "AtlasCloud Seedance 2.0 Reference-to-Video Upscaled": AtlasSeedance20ReferenceToVideoUpscaled,
    "AtlasCloud Seedance 2.0 Fast Text-to-Video Upscaled": AtlasSeedance20FastTextToVideoUpscaled,
    "AtlasCloud Seedance 2.0 Fast Image-to-Video Upscaled": AtlasSeedance20FastImageToVideoUpscaled,
    "AtlasCloud Seedance 2.0 Fast Reference-to-Video Upscaled": AtlasSeedance20FastReferenceToVideoUpscaled,
    "AtlasCloud WAN2.7 Text-to-Video": AtlasWan27TextToVideo,
    "AtlasCloud WAN2.7 Image-to-Video": AtlasWan27ImageToVideo,
    "AtlasCloud WAN2.7 Reference-to-Video": AtlasWan27ReferenceToVideo,
    "AtlasCloud WAN2.7 Video-Edit": AtlasWan27VideoEdit,
    "AtlasCloud HappyHorse 1.0 Text-to-Video": AtlasHappyHorse10TextToVideo,
    "AtlasCloud HappyHorse 1.0 Image-to-Video": AtlasHappyHorse10ImageToVideo,
    "AtlasCloud HappyHorse 1.0 Reference-to-Video": AtlasHappyHorse10ReferenceToVideo,
    "AtlasCloud HappyHorse 1.0 Video-Edit": AtlasHappyHorse10VideoEdit,
    "AtlasCloud HappyHorse 1.1 Text-to-Video": AtlasHappyHorse11TextToVideo,
    "AtlasCloud HappyHorse 1.1 Image-to-Video": AtlasHappyHorse11ImageToVideo,
    "AtlasCloud HappyHorse 1.1 Reference-to-Video": AtlasHappyHorse11ReferenceToVideo,
    "AtlasCloud VEO3.1 Lite Text-to-Video": AtlasVeo31LiteTextToVideo,
    "AtlasCloud VEO3.1 Lite Image-to-Video": AtlasVeo31LiteImageToVideo,
    "AtlasCloud VEO3.1 Lite Start-End Frame-to-Video": AtlasVeo31LiteStartEndFrameToVideo,
    "AtlasCloud Vidu Q3 Reference-to-Video": AtlasViduQ3ReferenceToVideo,
    "AtlasCloud Vidu Q3-Mix Reference-to-Video": AtlasViduQ3MixReferenceToVideo,
    "AtlasCloud Seedance V1.5 Pro Image-to-Video": AtlasSeedanceV15ProImageToVideo,
    "AtlasCloud Seedance V1.5 Pro Image-to-Video (Spicy)": AtlasSeedanceV15ProImageToVideoSpicy,
    "AtlasCloud Seedance V1.5 Pro Image-to-Video Fast": AtlasSeedanceV15ProImageToVideoFast,
    "AtlasCloud Seedream V4 Text-to-Image": AtlasSeedreamV4TextToImage,
    "AtlasCloud Seedream V4 Sequential Text-to-Image": AtlasSeedreamV4SequentialTextToImage,
    "AtlasCloud Seedream V4 Edit": AtlasSeedreamV4Edit,
    "AtlasCloud Seedream V4 Edit Sequential": AtlasSeedreamV4EditSequential,
    "AtlasCloud Seedream V4.5 Text-to-Image": AtlasSeedreamV45TextToImage,
    "AtlasCloud Seedream V4.5 Edit": AtlasSeedreamV45Edit,
    "AtlasCloud Seedream V4.5 Sequential Text-to-Image": AtlasSeedreamV45SequentialTextToImage,
    "AtlasCloud Seedream V4.5 Edit Sequential": AtlasSeedreamV45EditSequential,
    "AtlasCloud ZImage Turbo Lora Text-to-Image": AtlasZImageTurboLoraTextToImage,
    "AtlasCloud ZImage Turbo Text-to-Image": AtlasZImageTurboTextToImage,
    "AtlasCloud Nano Banana Pro Text-to-Image Ultra": AtlasNanoBananaProTextToImageUltra,
    "AtlasCloud Flux2 Flex Text-to-Image": AtlasFlux2FlexTextToImage,
    "AtlasCloud Flux Dev Text-to-Image": AtlasFluxDevTextToImage,
    "AtlasCloud Flux Dev LoRA Text-to-Image": AtlasFluxDevLoraTextToImage,
    "AtlasCloud Krea-2 Turbo Text-to-Image": AtlasKrea2TurboTextToImage,
    "AtlasCloud Flux Schnell Text-to-Image": AtlasFluxSchnellTextToImage,
    "AtlasCloud Flux Kontext Dev Edit": AtlasFluxKontextDevEdit,
    "AtlasCloud Flux Kontext Dev LoRA Edit": AtlasFluxKontextDevLoraEdit,
    "AtlasCloud Image Preview": AtlasImagePreviewURL,
    "AtlasCloud Video Preview": AtlasVideoPreviewer,
    "AtlasCloud Image to Base64": AtlasImageToBase64,
    "AtlasCloud Multi Image to Base64": AtlasMultiImageToBase64,
    "AtlasCloud Upload Videos to Asset": AtlasUploadVideosToAsset,
    "AtlasCloud Upload Audio to Asset": AtlasUploadAudioToAsset,
    "AtlasCloud Upload Audios to Asset": AtlasUploadAudiosToAsset,
    "AtlasCloud Multi Image to Seedance Assets": AtlasMultiImageToSeedanceAssets,
    "AtlasCloud Kling V3.0 Pro Text-to-Video": AtlasKlingV30ProTextToVideo,
    "AtlasCloud Kling V3.0 Std Text-to-Video": AtlasKlingV30StdTextToVideo,
    "AtlasCloud Kling V3.0 Std Image-to-Video": AtlasKlingV30StdImageToVideo,
    "AtlasCloud Kling V3.0 Pro Image-to-Video": AtlasKlingV30ProImageToVideo,
    "AtlasCloud Nano Banana 2 Text-to-Image": AtlasNanoBanana2TextToImage,
    "AtlasCloud Nano Banana 2 Text-to-Image Developer": AtlasNanoBanana2TextToImageDev,
    "AtlasCloud Nano Banana 2 Edit": AtlasNanoBanana2Edit,
    "AtlasCloud Nano Banana 2 Edit Developer": AtlasNanoBanana2EditDev,
    "AtlasCloud Nano Banana 2 Reference-to-Image": AtlasNanoBanana2ReferenceToImage,
    "AtlasCloud Nano Banana 2 Reference-to-Image Developer": AtlasNanoBanana2ReferenceToImageDev,
    "AtlasCloud Nano Banana 2 Lite Text-to-Image": AtlasNanoBanana2LiteTextToImage,
    "AtlasCloud Nano Banana 2 Lite Text-to-Image Developer": AtlasNanoBanana2LiteTextToImageDev,
    "AtlasCloud Nano Banana 2 Lite Edit": AtlasNanoBanana2LiteEdit,
    "AtlasCloud Nano Banana 2 Lite Edit Developer": AtlasNanoBanana2LiteEditDev,
    "AtlasCloud Nano Banana 2 Lite Reference-to-Image": AtlasNanoBanana2LiteReferenceToImage,
    "AtlasCloud HiDream O1 1.5 Text-to-Image": AtlasHiDreamO115TextToImage,
    "AtlasCloud HiDream O1 1.5 Edit": AtlasHiDreamO115Edit,
    "AtlasCloud Reve 2.1 Text-to-Image": AtlasReve21TextToImage,
    "AtlasCloud Reve 2.1 Edit": AtlasReve21Edit,
    "AtlasCloud Reve 2.1 Remix": AtlasReve21Remix,
    "AtlasCloud Sync Lipsync v3": AtlasSyncLipsyncV3,
    "AtlasCloud VEED Lipsync": AtlasVeedLipsync,
    "AtlasCloud Seedream V5.0 Lite Text-to-Image": AtlasSeedreamV50LiteTextToImage,
    "AtlasCloud Seedream V5.0 Lite Sequential Text-to-Image": AtlasSeedreamV50LiteSequentialTextToImage,
    "AtlasCloud Seedream V5.0 Lite Edit": AtlasSeedreamV50LiteEdit,
    "AtlasCloud Seedream V5.0 Lite Edit Sequential": AtlasSeedreamV50LiteEditSequential,
    "AtlasCloud Vidu Q3 Text-to-Video": AtlasViduQ3TextToVideo,
    "AtlasCloud Vidu Q3 Image-to-Video": AtlasViduQ3ImageToVideo,
    "AtlasCloud Vidu Q3 Image-to-Video (Q3 API)": AtlasViduQ3ImageToVideoV2,
    "AtlasCloud Vidu Q3-Pro Text-to-Video": AtlasViduQ3ProTextToVideo,
    "AtlasCloud Vidu Q3-Pro Image-to-Video": AtlasViduQ3ProImageToVideo,
    "AtlasCloud Vidu Q3-Pro Start-End-to-Video": AtlasViduQ3ProStartEndToVideo,
    "AtlasCloud Vidu Q3-Turbo Text-to-Video": AtlasViduQ3TurboTextToVideo,
    "AtlasCloud Vidu Q3-Turbo Image-to-Video": AtlasViduQ3TurboImageToVideo,
    "AtlasCloud Vidu Q3-Turbo Start-End-to-Video": AtlasViduQ3TurboStartEndToVideo,
    "AtlasCloud WAN2.2 Spicy Image-to-Video": AtlasWan22SpicyImageToVideo,
    "AtlasCloud WAN2.2 Turbo Image-to-Video": AtlasWan22TurboImageToVideo,
    "AtlasCloud WAN2.2 Turbo Spicy Image-to-Video": AtlasWan22TurboSpicyImageToVideo,
    "AtlasCloud WAN2.2 Turbo Spicy Image-to-Video LoRA": AtlasWan22TurboSpicyImageToVideoLora,
    "AtlasCloud WAN2.2 Spicy Image-to-Video LoRA": AtlasWan22SpicyImageToVideoLora,
    "AtlasCloud VEO3 Text-to-Video": AtlasVeo3TextToVideo,
    "AtlasCloud Imagen4 Text-to-Image": AtlasImagen4TextToImage,
    "AtlasCloud Imagen4 Fast Text-to-Image": AtlasImagen4FastTextToImage,
    "AtlasCloud Luma Ray 2 Text-to-Video": AtlasLumaRay2TextToVideo,
    "AtlasCloud Luma Ray 2 Image-to-Video": AtlasLumaRay2ImageToVideo,
    "AtlasCloud Pika V2.2 Text-to-Video": AtlasPikaV22TextToVideo,
    "AtlasCloud PixVerse V4.5 Text-to-Video": AtlasPixVerseV45TextToVideo,
    "AtlasCloud PixVerse C1 Text-to-Video": AtlasPixVerseC1TextToVideo,
    "AtlasCloud PixVerse C1 Image-to-Video": AtlasPixVerseC1ImageToVideo,
    "AtlasCloud PixVerse C1 Reference-to-Video": AtlasPixVerseC1ReferenceToVideo,
    "AtlasCloud PixVerse V6 Text-to-Video": AtlasPixVerseV6TextToVideo,
    "AtlasCloud PixVerse V6 Image-to-Video": AtlasPixVerseV6ImageToVideo,
    "AtlasCloud PixVerse V6 Reference-to-Video": AtlasPixVerseV6ReferenceToVideo,
    "AtlasCloud PixVerse V6 Video-Extend": AtlasPixVerseV6VideoExtend,
    "AtlasCloud PixVerse C1 Start-End-to-Video": AtlasPixVerseC1StartEndToVideo,
    "AtlasCloud PixVerse V6 Start-End-to-Video": AtlasPixVerseV6StartEndToVideo,
    "AtlasCloud Midjourney V8.1 Image-to-Video": AtlasMidjourneyV81ImageToVideo,
    "AtlasCloud Midjourney V8.1 Text-to-Image": AtlasMidjourneyV81TextToImage,
    "AtlasCloud Midjourney V8.1 Image-to-Image": AtlasMidjourneyV81ImageToImage,
    "AtlasCloud Midjourney V8.1 Blend": AtlasMidjourneyV81Blend,
    "AtlasCloud Midjourney V8.1 Remove Background": AtlasMidjourneyV81RemoveBackground,
    "AtlasCloud Midjourney V8.1 Style Transfer": AtlasMidjourneyV81StyleTransfer,
    "AtlasCloud Youchuan V8.1 Image-to-Video": AtlasYouchuanV81ImageToVideo,
    "AtlasCloud Youchuan V8.1 Text-to-Image": AtlasYouchuanV81TextToImage,
    "AtlasCloud Youchuan V8.1 Image-to-Image": AtlasYouchuanV81ImageToImage,
    "AtlasCloud Youchuan V8.1 Blend": AtlasYouchuanV81Blend,
    "AtlasCloud Youchuan V8.1 Remove Background": AtlasYouchuanV81RemoveBackground,
    "AtlasCloud Youchuan V8.1 Style Transfer": AtlasYouchuanV81StyleTransfer,
    "AtlasCloud Kling V3.0 4K Image-to-Video": AtlasKlingV304KImageToVideo,
    "AtlasCloud Kling V3.0 4K Text-to-Video": AtlasKlingV304KTextToVideo,
    "AtlasCloud Kling V3.0 Turbo Image-to-Video": AtlasKlingV30TurboImageToVideo,
    "AtlasCloud Kling V3.0 Turbo Text-to-Video": AtlasKlingV30TurboTextToVideo,
    "AtlasCloud Kling Video O3 4K Image-to-Video": AtlasKlingVideoO34KImageToVideo,
    "AtlasCloud Kling Video O3 4K Text-to-Video": AtlasKlingVideoO34KTextToVideo,
    "AtlasCloud Hailuo 02 T2V Pro": AtlasHailuo02T2VPro,
    "AtlasCloud Sora 2 Image-to-Video": AtlasSora2ImageToVideo,
    "AtlasCloud Kling V2.5 Turbo Pro Text-to-Video": AtlasKlingV25TurboProTextToVideo,
    "AtlasCloud Hunyuan Text-to-Video": AtlasHunyuanTextToVideo,
    "AtlasCloud VEO3 Fast Text-to-Video": AtlasVeo3FastTextToVideo,
    "AtlasCloud VEO3.1 Fast Text-to-Video": AtlasVeo31FastTextToVideo,
    "AtlasCloud VEO3.1 Fast Image-to-Video": AtlasVeo31FastImageToVideo,
    "AtlasCloud Gemini Omni Flash Text-to-Video Developer": AtlasGeminiOmniFlashTextToVideoDev,
    "AtlasCloud Gemini Omni Flash Image-to-Video Developer": AtlasGeminiOmniFlashImageToVideoDev,
    "AtlasCloud Gemini Omni Flash Reference-to-Video Developer": AtlasGeminiOmniFlashReferenceToVideoDev,
    "AtlasCloud Gemini Omni Flash Text-to-Video": AtlasGeminiOmniFlashTextToVideo,
    "AtlasCloud Gemini Omni Flash Image-to-Video": AtlasGeminiOmniFlashImageToVideo,
    "AtlasCloud Gemini Omni Flash Reference-to-Video": AtlasGeminiOmniFlashReferenceToVideo,
    "AtlasCloud Gemini Omni Flash Video Edit": AtlasGeminiOmniFlashVideoEdit,
    "AtlasCloud VEO3.1 Reference-to-Video": AtlasVeo31ReferenceToVideo,
    "AtlasCloud VEO3.1 Image-to-Video": AtlasVeo31ImageToVideo,
    "AtlasCloud VEO3 Image-to-Video": AtlasVeo3ImageToVideo,
    "AtlasCloud VEO2 Text-to-Video": AtlasVeo2TextToVideo,
    "AtlasCloud VEO2 Image-to-Video": AtlasVeo2ImageToVideo,
    "AtlasCloud Luma Ray 2 Flash Text-to-Video": AtlasLumaRay2FlashTextToVideo,
    "AtlasCloud Pika V2.0 Turbo Text-to-Video": AtlasPikaV20TurboTextToVideo,
    "AtlasCloud Pika V2.1 Image-to-Video": AtlasPikaV21ImageToVideo,
    "AtlasCloud PixVerse V4.5 Image-to-Video": AtlasPixVerseV45ImageToVideo,
    "AtlasCloud Hailuo 02 I2V Pro": AtlasHailuo02I2VPro,
    "AtlasCloud Hailuo 02 I2V Standard": AtlasMinimaxHailuo02I2VStandard,
    "AtlasCloud Hailuo 02 Standard": AtlasHailuo02I2VStandard,
    "AtlasCloud Sora 2 Image-to-Video Pro": AtlasSora2ImageToVideoPro,
    "AtlasCloud Sora 2 Text-to-Video": AtlasSora2TextToVideo,
    "AtlasCloud Kling V2.5 Turbo Pro Image-to-Video": AtlasKlingV25TurboProImageToVideo,
    "AtlasCloud Hunyuan Image-to-Video": AtlasHunyuanImageToVideo,
    "AtlasCloud WAN2.5 Image-to-Video": AtlasWAN25ImageToVideo,
    "AtlasCloud WAN2.2 Image-to-Video 720p": AtlasAlibabaWan22I2V720p,
    "AtlasCloud WAN2.2 Image-to-Video 480p": AtlasAlibabaWan22I2V480p,
    "AtlasCloud WAN2.2 Animate Mix": AtlasWan22AnimateMix,
    "AtlasCloud WAN2.2 Animate Move": AtlasWan22AnimateMove,
    "AtlasCloud Wan 2.2 Turbo Infinite Image-to-Video": AtlasWan22TurboInfiniteImageToVideo,
    "AtlasCloud Wan 2.2 Turbo Infinite Image-to-Video LoRA": AtlasWan22TurboInfiniteImageToVideoLoRA,
    "AtlasCloud Wan 2.2 Turbo Spicy Infinite Image-to-Video": AtlasWan22TurboSpicyInfiniteImageToVideo,
    "AtlasCloud Wan 2.2 Turbo Spicy Infinite Image-to-Video LoRA": AtlasWan22TurboSpicyInfiniteImageToVideoLoRA,
    "AtlasCloud WAN2.6 Spicy Image-to-Video": AtlasWan26SpicyImageToVideo,
    "AtlasCloud WAN2.7 Spicy Image-to-Video": AtlasWan27SpicyImageToVideo,
    "AtlasCloud Imagen4 Ultra Text-to-Image": AtlasImagen4UltraTextToImage,
    "AtlasCloud Imagen3 Text-to-Image": AtlasImagen3TextToImage,
    "AtlasCloud Imagen3 Fast Text-to-Image": AtlasImagen3FastTextToImage,
    "AtlasCloud Ideogram V3 Quality Text-to-Image": AtlasIdeogramV3QualityTextToImage,
    "AtlasCloud Ideogram V3 Turbo Text-to-Image": AtlasIdeogramV3TurboTextToImage,
    "AtlasCloud Luma Photon Text-to-Image": AtlasLumaPhotonTextToImage,
    "AtlasCloud Luma Photon Flash Text-to-Image": AtlasLumaPhotonFlashTextToImage,
    "AtlasCloud Recraft V3 Text-to-Image": AtlasRecraftV3TextToImage,
    "AtlasCloud Qwen Image Edit": AtlasQwenImageEdit,
    "AtlasCloud Qwen Image Text-to-Image (AtlasCloud)": AtlasAtlascloudQwenImageTextToImage,
    "AtlasCloud Qwen Image Edit (Alibaba)": AtlasAlibabaQwenImageEdit,
    "AtlasCloud Qwen Image Edit Plus (Alibaba)": AtlasAlibabaQwenImageEditPlus,
    "AtlasCloud Nano Banana Pro Text-to-Image": AtlasNanoBananaProTextToImage,
    "AtlasCloud Nano Banana Pro Text-to-Image Developer": AtlasNanoBananaProTextToImageDeveloper,
    "AtlasCloud Nano Banana Pro Edit": AtlasNanoBananaProEdit,
    "AtlasCloud Nano Banana Pro Edit Ultra": AtlasNanoBananaProEditUltra,
    "AtlasCloud Nano Banana Pro Edit Developer": AtlasNanoBananaProEditDeveloper,
    "AtlasCloud Nano Banana Text-to-Image": AtlasNanoBananaTextToImage,
    "AtlasCloud Nano Banana Text-to-Image Developer": AtlasNanoBananaTextToImageDeveloper,
    "AtlasCloud Nano Banana Edit": AtlasNanoBananaEdit,
    "AtlasCloud Nano Banana Edit Developer": AtlasNanoBananaEditDeveloper,
    "AtlasCloud Qwen Image Edit Plus 20251215": AtlasQwenImageEditPlus20251215,
    "AtlasCloud Qwen Image Text-to-Image Plus": AtlasQwenImageTextToImagePlus,
    "AtlasCloud Qwen Image Text-to-Image Max": AtlasQwenImageTextToImageMax,
    "AtlasCloud GPT Image-1 Text-to-Image": AtlasOpenAIGPTImage1TextToImage,
    "AtlasCloud GPT Image-1 Edit": AtlasOpenAIGPTImage1Edit,
    "AtlasCloud GPT Image-1 Mini Text-to-Image": AtlasOpenAIGPTImage1MiniTextToImage,
    "AtlasCloud GPT Image-1 Mini Edit": AtlasOpenAIGPTImage1MiniEdit,
    "AtlasCloud GPT Image-1.5 Text-to-Image": AtlasOpenAIGPTImage15TextToImage,
    "AtlasCloud GPT Image-1.5 Edit": AtlasOpenAIGPTImage15Edit,
    "AtlasCloud GPT Image-2 Text-to-Image": AtlasOpenAIGPTImage2TextToImage,
    "AtlasCloud GPT Image-2 Edit": AtlasOpenAIGPTImage2Edit,
    "AtlasCloud GPT Image-2 Developer Text-to-Image": AtlasOpenAIGPTImage2DeveloperTextToImage,
    "AtlasCloud GPT Image-2 Developer Edit": AtlasOpenAIGPTImage2DeveloperEdit,
    "AtlasCloud Qwen Image 2.0 Text-to-Image": AtlasQwenImage20TextToImage,
    "AtlasCloud Qwen Image 2.0 Edit": AtlasQwenImage20Edit,
    "AtlasCloud Qwen Image 2.0 Pro Text-to-Image": AtlasQwenImage20ProTextToImage,
    "AtlasCloud Qwen Image 2.0 Pro Edit": AtlasQwenImage20ProEdit,
    "AtlasCloud Seedance V1 Pro Fast Text-to-Video": AtlasSeedanceV1ProFastTextToVideo,
    "AtlasCloud Seedance V1 Pro Fast Image-to-Video": AtlasSeedanceV1ProFastImageToVideo,
    "AtlasCloud Seedance V1 Pro Image-to-Video 1080p": AtlasBytedanceSeedanceV1ProI2V1080p,
    "AtlasCloud Seedance V1 Pro Image-to-Video 720p": AtlasBytedanceSeedanceV1ProI2V720p,
    "AtlasCloud Seedance V1 Pro Image-to-Video 480p": AtlasBytedanceSeedanceV1ProI2V480p,
    "AtlasCloud Seedance V1 Lite Image-to-Video 720p": AtlasBytedanceSeedanceV1LiteI2V720p,
    "AtlasCloud Seedance V1 Lite Image-to-Video 480p": AtlasBytedanceSeedanceV1LiteI2V480p,
    "AtlasCloud WAN2.5 Text-to-Video Fast": AtlasWAN25TextToVideoFast,
    "AtlasCloud WAN2.5 Image-to-Video Fast": AtlasWAN25ImageToVideoFast,
    "AtlasCloud Van-2.5 Text-to-Video": AtlasAtlascloudVan25TextToVideo,
    "AtlasCloud Van-2.5 Image-to-Video": AtlasAtlascloudVan25ImageToVideo,
    "AtlasCloud Van-2.6 Text-to-Video": AtlasVan26TextToVideo,
    "AtlasCloud Van-2.6 Image-to-Video": AtlasVan26ImageToVideo,
    "AtlasCloud InfiniteTalk Audio-to-Video": AtlasInfiniteTalkAudioToVideo,
    "AtlasCloud Vidu Q1 Text-to-Video": AtlasViduQ1TextToVideo,
    "AtlasCloud Vidu Q1 Image-to-Video": AtlasViduQ1ImageToVideo,
    "AtlasCloud Vidu Q1 Start-End-to-Video": AtlasViduQ1StartEndToVideo,
    "AtlasCloud Vidu Q1 Reference-to-Video": AtlasViduQ1ReferenceToVideo,
    "AtlasCloud Vidu Q2 Text-to-Video": AtlasViduQ2TextToVideo,
    "AtlasCloud Vidu Q2 Reference-to-Video": AtlasViduQ2ReferenceToVideo,
    "AtlasCloud Vidu Q2-Pro Image-to-Video": AtlasViduQ2ProImageToVideo,
    "AtlasCloud Vidu Q2-Pro Start-End-to-Video": AtlasViduQ2ProStartEndToVideo,
    "AtlasCloud Vidu Q2-Pro Reference-to-Video": AtlasViduQ2ProReferenceToVideo,
    "AtlasCloud Vidu Q2-Pro-Fast Image-to-Video": AtlasViduQ2ProFastImageToVideo,
    "AtlasCloud Vidu Q2-Pro-Fast Start-End-to-Video": AtlasViduQ2ProFastStartEndToVideo,
    "AtlasCloud Vidu Q2-Turbo Image-to-Video": AtlasViduQ2TurboImageToVideo,
    "AtlasCloud Vidu Q2-Turbo Start-End-to-Video": AtlasViduQ2TurboStartEndToVideo,
    "AtlasCloud Vidu Reference-to-Video Q1": AtlasViduReferenceToVideoQ1,
    "AtlasCloud Vidu Reference-to-Video 2.0": AtlasViduReferenceToVideoV2,
    "AtlasCloud Vidu Q2-Pro-Fast Reference-to-Video": AtlasViduQ2ProFastReferenceToVideo,
    "AtlasCloud Vidu Q2-Pro-Fast Reference-to-Video (with Audio)": AtlasViduQ2ProFastReferenceToVideoWithAudio,
    "AtlasCloud Vidu Start-End-to-Video 2.0": AtlasViduStartEndToVideoV2,
    "AtlasCloud Video Upscaler (Video-to-Video)": AtlasVideoUpscalerVideoToVideo,
    "AtlasCloud Veed Fabric 1.0 Image-to-Video": AtlasVeedFabric10ImageToVideo,
    "AtlasCloud Veed Fabric 1.0 Fast Image-to-Video": AtlasVeedFabric10FastImageToVideo,
    "AtlasCloud Grok Imagine IQ Text-to-Image": AtlasGrokImagineImageQualityTextToImage,
    "AtlasCloud Grok Imagine IQ Edit": AtlasGrokImagineImageQualityEdit,
    "AtlasCloud Grok Imagine Text-to-Image": AtlasGrokImagineImageTextToImage,
    "AtlasCloud Grok Imagine Edit": AtlasGrokImagineImageEdit,
    "AtlasCloud Kling V2.0 I2V Master": AtlasKlingV20I2VMaster,
    "AtlasCloud VEO3 Fast Image-to-Video": AtlasVeo3FastImageToVideo,
    "AtlasCloud Kling V2.1 T2V Master": AtlasKlingV21T2VMaster,
    "AtlasCloud Kling V2.1 I2V Master": AtlasKlingV21I2VMaster,
    "AtlasCloud Kling V2.1 I2V Pro (Start/End Frame)": AtlasKlingV21I2VProStartEndFrame,
    "AtlasCloud Kling V2.1 I2V Pro": AtlasKwaivgiKlingV21I2VPro,
    "AtlasCloud Kling V2.1 I2V Standard": AtlasKwaivgiKlingV21I2VStandard,
    "AtlasCloud Kling V1.6 Multi I2V Pro": AtlasKlingV16MultiI2VPro,
    "AtlasCloud Kling V1.6 Multi I2V Standard": AtlasKlingV16MultiI2VStandard,
    "AtlasCloud Kling V1.6 I2V Standard": AtlasKlingV16I2VStandard,
    "AtlasCloud Kling V1.6 T2V Standard": AtlasKwaivgiKlingV16T2VStandard,
    "AtlasCloud Kling V1.6 I2V Pro": AtlasKwaivgiKlingV16I2VPro,
    "AtlasCloud Kling Effects": AtlasKlingEffects,
    "AtlasCloud Hailuo 2.3 T2V Standard": AtlasHailuo23T2VStandard,
    "AtlasCloud Hailuo 2.3 I2V Standard": AtlasHailuo23I2VStandard,
    "AtlasCloud Hailuo 2.3 I2V Pro": AtlasHailuo23I2VPro,
    "AtlasCloud Hailuo 2.3 Fast": AtlasHailuo23Fast,
    "AtlasCloud Hailuo 02 Fast": AtlasHailuo02Fast,
    "AtlasCloud Hailuo 02 Pro": AtlasHailuo02Pro,
    "AtlasCloud Hailuo 02 T2V Standard": AtlasHailuo02T2VStandard,
    "AtlasCloud Seedance V1 Lite T2V 1080p": AtlasSeedanceV1LiteT2V1080p,
    "AtlasCloud Seedance V1 Lite T2V 720p": AtlasSeedanceV1LiteT2V720p,
    "AtlasCloud Seedance V1 Lite I2V 1080p": AtlasSeedanceV1LiteI2V1080p,
    "AtlasCloud Kling V2.0 T2V Master": AtlasKlingV20T2VMaster,
    "AtlasCloud Grok Imagine Video Text-to-Video": AtlasGrokImagineVideoTextToVideo,
    "AtlasCloud Grok Imagine Video Image-to-Video": AtlasGrokImagineVideoImageToVideo,
    "AtlasCloud Grok Imagine Video v1.5 Image-to-Video": AtlasGrokImagineVideoV15ImageToVideo,
    "AtlasCloud Grok Imagine Video Reference-to-Video": AtlasGrokImagineVideoReferenceToVideo,
    "AtlasCloud FLUX.2 Pro Text-to-Image": AtlasFlux2ProTextToImage,
    "AtlasCloud FLUX.2 Flex Edit": AtlasFlux2FlexEdit,
    "AtlasCloud FLUX.2 Pro Edit": AtlasFlux2ProEdit,
    "AtlasCloud Grok Imagine Video Edit": AtlasGrokImagineVideoEdit,
    "AtlasCloud Grok Imagine Video Extend": AtlasGrokImagineVideoExtend,
    "AtlasCloud Seedream V5.0 Pro Text-to-Image": AtlasSeedreamV50ProTextToImage,
    "AtlasCloud Seedream V5.0 Pro Edit": AtlasSeedreamV50ProEdit,
    "AtlasCloud Cosmos 3 Super Text-to-Image": AtlasCosmos3SuperTextToImage,
    "AtlasCloud Cosmos 3 Super Image-to-Video": AtlasCosmos3SuperImageToVideo,
    "AtlasCloud Ideogram V4 Turbo Text-to-Image": AtlasIdeogramV4TurboTextToImage,
    "AtlasCloud Ideogram V4 Quality Text-to-Image": AtlasIdeogramV4QualityTextToImage,
    "AtlasCloud LTX 2.3 Quality Text-to-Video": AtlasLtx23QualityTextToVideo,
    "AtlasCloud LTX 2.3 Quality Image-to-Video": AtlasLtx23QualityImageToVideo,
    "AtlasCloud LTX 2.3 Quality Extend Video": AtlasLtx23QualityExtendVideo,
}


NODE_DISPLAY_NAME_MAPPINGS: Dict[str, str] = {
    "AtlasCloud Client": "AtlasCloud Client (API Key/Base URL)",
    "AtlasCloud WAN2.5 Text-to-Video": "AtlasCloud WAN2.5 Text-to-Video",
    "AtlasCloud WAN2.6 Text-to-Video": "AtlasCloud WAN2.6 Text-to-Video",
    "AtlasCloud WAN2.6 Text-to-Image": "AtlasCloud WAN2.6 Text-to-Image",
    "AtlasCloud WAN2.7 Text-to-Image": "AtlasCloud WAN2.7 Text-to-Image",
    "AtlasCloud WAN2.7 Image-Edit": "AtlasCloud WAN2.7 Image-Edit",
    "AtlasCloud WAN2.7 Pro Text-to-Image": "AtlasCloud WAN2.7 Pro Text-to-Image",
    "AtlasCloud WAN2.7 Pro Image-Edit": "AtlasCloud WAN2.7 Pro Image-Edit",
    "AtlasCloud WAN2.5 Text-to-Image": "AtlasCloud WAN2.5 Text-to-Image",
    "AtlasCloud Baidu ERNIE-Image-Turbo Text-to-Image": "AtlasCloud Baidu ERNIE-Image-Turbo Text-to-Image",
    "AtlasCloud MAI-Image-2.5 Text-to-Image": "AtlasCloud MAI-Image-2.5 Text-to-Image",
    "AtlasCloud MAI-Image-2.5-Flash Text-to-Image": "AtlasCloud MAI-Image-2.5-Flash Text-to-Image",
    "AtlasCloud MAI-Image-2.5 Edit": "AtlasCloud MAI-Image-2.5 Edit",
    "AtlasCloud MAI-Image-2.5-Flash Edit": "AtlasCloud MAI-Image-2.5-Flash Edit",
    "AtlasCloud WAN2.5 Image-Edit": "AtlasCloud WAN2.5 Image-Edit",
    "AtlasCloud WAN2.6 Image-Edit": "AtlasCloud WAN2.6 Image-Edit",
    "AtlasCloud WAN2.6 Image-to-Video": "AtlasCloud WAN2.6 Image-to-Video",
    "AtlasCloud WAN2.6 Image-to-Video Flash": "AtlasCloud WAN2.6 Image-to-Video Flash",
    "AtlasCloud WAN2.6 Video-to-Video": "AtlasCloud WAN2.6 Video-to-Video",
    "AtlasCloud WAN2.2 Spicy Video Extend": "AtlasCloud WAN2.2 Spicy Video Extend",
    "AtlasCloud WAN2.2 Spicy Video Extend LoRA": "AtlasCloud WAN2.2 Spicy Video Extend LoRA",
    "AtlasCloud WAN2.5 Video Extend": "AtlasCloud WAN2.5 Video Extend",
    "AtlasCloud WAN2.2 (AtlasCloud) Image-to-Video": "AtlasCloud WAN2.2 (AtlasCloud) Image-to-Video",
    "AtlasCloud WAN2.2 (AtlasCloud) Image-to-Video LoRA": "AtlasCloud WAN2.2 (AtlasCloud) Image-to-Video LoRA",
    "AtlasCloud Kling Video O3 Pro Text-to-Video": "AtlasCloud Kling Video O3 Pro Text-to-Video",
    "AtlasCloud Kling Video O3 Pro Image-to-Video": "AtlasCloud Kling Video O3 Pro Image-to-Video",
    "AtlasCloud Kling Video O3 Pro Reference-to-Video": "AtlasCloud Kling Video O3 Pro Reference-to-Video",
    "AtlasCloud Kling Video O3 Pro Video-Edit": "AtlasCloud Kling Video O3 Pro Video-Edit",
    "AtlasCloud Kling Video O3 Std Text-to-Video": "AtlasCloud Kling Video O3 Std Text-to-Video",
    "AtlasCloud Kling Video O3 Std Image-to-Video": "AtlasCloud Kling Video O3 Std Image-to-Video",
    "AtlasCloud Kling Video O3 Std Reference-to-Video": "AtlasCloud Kling Video O3 Std Reference-to-Video",
    "AtlasCloud Kling Video O3 Std Video-Edit": "AtlasCloud Kling Video O3 Std Video-Edit",
    "AtlasCloud WAN2.2 Text-to-Video 720p": "AtlasCloud WAN2.2 Text-to-Video 720p",
    "AtlasCloud WAN2.2 Text-to-Video 480p": "AtlasCloud WAN2.2 Text-to-Video 480p",
    "AtlasCloud VEO3.1 Text-to-Video": "AtlasCloud VEO3.1 Text-to-Video",
    "AtlasCloud Kling V2.6 Pro Text-to-Video": "AtlasCloud Kling V2.6 Pro Text-to-Video",
    "AtlasCloud Kling V2.6 Pro Avatar": "AtlasCloud Kling V2.6 Pro Avatar",
    "AtlasCloud Kling V2.6 Std Avatar": "AtlasCloud Kling V2.6 Std Avatar",
    "AtlasCloud Kling V2.6 Pro Motion-Control": "AtlasCloud Kling V2.6 Pro Motion-Control",
    "AtlasCloud Kling V2.6 Std Motion-Control": "AtlasCloud Kling V2.6 Std Motion-Control",
    "AtlasCloud Kling V2.6 Pro Image-to-Video": "AtlasCloud Kling V2.6 Pro Image-to-Video",
    "AtlasCloud Kling Video O1 Text-to-Video": "AtlasCloud Kling Video O1 Text-to-Video",
    "AtlasCloud Kling Video O1 Image-to-Video": "AtlasCloud Kling Video O1 Image-to-Video",
    "AtlasCloud Seedance V1 Pro Text-to-Video 1080p": "AtlasCloud Seedance V1 Pro Text-to-Video 1080p",
    "AtlasCloud Seedance V1 Pro Text-to-Video 720p": "AtlasCloud Seedance V1 Pro Text-to-Video 720p",
    "AtlasCloud Seedance V1 Pro Text-to-Video 480p": "AtlasCloud Seedance V1 Pro Text-to-Video 480p",
    "AtlasCloud Seedance V1 Lite Text-to-Video 480p": "AtlasCloud Seedance V1 Lite Text-to-Video 480p",
    "AtlasCloud Hailuo 2.3 Pro Text-to-Video": "AtlasCloud Hailuo 2.3 Pro Text-to-Video",
    "AtlasCloud Sora 2 Text-to-Video Pro": "AtlasCloud Sora 2 Text-to-Video Pro",
    "AtlasCloud Seedance V1.5 Pro Text-to-Video": "AtlasCloud Seedance V1.5 Pro Text-to-Video",
    "AtlasCloud Seedance 2.0 Text-to-Video": "AtlasCloud Seedance 2.0 Text-to-Video",
    "AtlasCloud Seedance 2.0 Image-to-Video": "AtlasCloud Seedance 2.0 Image-to-Video",
    "AtlasCloud Seedance 2.0 Reference-to-Video": "AtlasCloud Seedance 2.0 Reference-to-Video",
    "AtlasCloud Seedance 2.5 Text-to-Video": "AtlasCloud Seedance 2.5 Text-to-Video",
    "AtlasCloud Seedance 2.5 Image-to-Video": "AtlasCloud Seedance 2.5 Image-to-Video",
    "AtlasCloud Seedance 2.5 Reference-to-Video": "AtlasCloud Seedance 2.5 Reference-to-Video",
    "AtlasCloud Seedance 2.5 Reference-to-Video (Multi 30img/10vid)": "AtlasCloud Seedance 2.5 Reference-to-Video (Multi 30img/10vid)",
    "AtlasCloud Seedance 2.0 Fast Text-to-Video": "AtlasCloud Seedance 2.0 Fast Text-to-Video",
    "AtlasCloud Seedance 2.0 Fast Image-to-Video": "AtlasCloud Seedance 2.0 Fast Image-to-Video",
    "AtlasCloud Seedance 2.0 Fast Reference-to-Video": "AtlasCloud Seedance 2.0 Fast Reference-to-Video",
    "AtlasCloud Seedance 2.0 Mini Text-to-Video": "AtlasCloud Seedance 2.0 Mini Text-to-Video",
    "AtlasCloud Seedance 2.0 Mini Image-to-Video": "AtlasCloud Seedance 2.0 Mini Image-to-Video",
    "AtlasCloud Seedance 2.0 Mini Reference-to-Video": "AtlasCloud Seedance 2.0 Mini Reference-to-Video",
    "AtlasCloud Avatar Omni Human 1.5": "AtlasCloud Avatar Omni Human 1.5",
    "AtlasCloud Image Upscaler": "AtlasCloud Image Upscaler",
    "AtlasCloud Face Swap (Image)": "AtlasCloud Face Swap (Image)",
    "AtlasCloud Photo Cleanup": "AtlasCloud Photo Cleanup",
    "AtlasCloud Face Swap (Video)": "AtlasCloud Face Swap (Video)",
    "AtlasCloud Seedance 2.0 Text-to-Video Upscaled": "AtlasCloud Seedance 2.0 Text-to-Video Upscaled",
    "AtlasCloud Seedance 2.0 Image-to-Video Upscaled": "AtlasCloud Seedance 2.0 Image-to-Video Upscaled",
    "AtlasCloud Seedance 2.0 Reference-to-Video Upscaled": "AtlasCloud Seedance 2.0 Reference-to-Video Upscaled",
    "AtlasCloud Seedance 2.0 Fast Text-to-Video Upscaled": "AtlasCloud Seedance 2.0 Fast Text-to-Video Upscaled",
    "AtlasCloud Seedance 2.0 Fast Image-to-Video Upscaled": "AtlasCloud Seedance 2.0 Fast Image-to-Video Upscaled",
    "AtlasCloud Seedance 2.0 Fast Reference-to-Video Upscaled": "AtlasCloud Seedance 2.0 Fast Reference-to-Video Upscaled",
    "AtlasCloud WAN2.7 Text-to-Video": "AtlasCloud WAN2.7 Text-to-Video",
    "AtlasCloud WAN2.7 Image-to-Video": "AtlasCloud WAN2.7 Image-to-Video",
    "AtlasCloud WAN2.7 Reference-to-Video": "AtlasCloud WAN2.7 Reference-to-Video",
    "AtlasCloud WAN2.7 Video-Edit": "AtlasCloud WAN2.7 Video-Edit",
    "AtlasCloud HappyHorse 1.0 Text-to-Video": "AtlasCloud HappyHorse 1.0 Text-to-Video",
    "AtlasCloud HappyHorse 1.0 Image-to-Video": "AtlasCloud HappyHorse 1.0 Image-to-Video",
    "AtlasCloud HappyHorse 1.0 Reference-to-Video": "AtlasCloud HappyHorse 1.0 Reference-to-Video",
    "AtlasCloud HappyHorse 1.0 Video-Edit": "AtlasCloud HappyHorse 1.0 Video-Edit",
    "AtlasCloud HappyHorse 1.1 Text-to-Video": "AtlasCloud HappyHorse 1.1 Text-to-Video",
    "AtlasCloud HappyHorse 1.1 Image-to-Video": "AtlasCloud HappyHorse 1.1 Image-to-Video",
    "AtlasCloud HappyHorse 1.1 Reference-to-Video": "AtlasCloud HappyHorse 1.1 Reference-to-Video",
    "AtlasCloud VEO3.1 Lite Text-to-Video": "AtlasCloud VEO3.1 Lite Text-to-Video",
    "AtlasCloud VEO3.1 Lite Image-to-Video": "AtlasCloud VEO3.1 Lite Image-to-Video",
    "AtlasCloud VEO3.1 Lite Start-End Frame-to-Video": "AtlasCloud VEO3.1 Lite Start-End Frame-to-Video",
    "AtlasCloud Vidu Q3 Reference-to-Video": "AtlasCloud Vidu Q3 Reference-to-Video",
    "AtlasCloud Vidu Q3-Mix Reference-to-Video": "AtlasCloud Vidu Q3-Mix Reference-to-Video",
    "AtlasCloud Seedance V1.5 Pro Text-to-Video Fast": "AtlasCloud Seedance V1.5 Pro Text-to-Video Fast",
    "AtlasCloud Seedance V1.5 Pro Image-to-Video": "AtlasCloud Seedance V1.5 Pro Image-to-Video",
    "AtlasCloud Seedance V1.5 Pro Image-to-Video (Spicy)": "AtlasCloud Seedance V1.5 Pro Image-to-Video (Spicy)",
    "AtlasCloud Seedance V1.5 Pro Image-to-Video Fast": "AtlasCloud Seedance V1.5 Pro Image-to-Video Fast",
    "AtlasCloud Seedream V4 Text-to-Image": "AtlasCloud Seedream V4 Text-to-Image",
    "AtlasCloud Seedream V4 Sequential Text-to-Image": "AtlasCloud Seedream V4 Sequential Text-to-Image",
    "AtlasCloud Seedream V4 Edit": "AtlasCloud Seedream V4 Edit",
    "AtlasCloud Seedream V4 Edit Sequential": "AtlasCloud Seedream V4 Edit Sequential",
    "AtlasCloud Seedream V4.5 Text-to-Image": "AtlasCloud Seedream V4.5 Text-to-Image",
    "AtlasCloud Seedream V4.5 Edit": "AtlasCloud Seedream V4.5 Edit",
    "AtlasCloud Seedream V4.5 Sequential Text-to-Image": "AtlasCloud Seedream V4.5 Sequential Text-to-Image",
    "AtlasCloud Seedream V4.5 Edit Sequential": "AtlasCloud Seedream V4.5 Edit Sequential",
    "AtlasCloud Image Preview": "AtlasCloud Image Preview",
    "AtlasCloud ZImage Turbo Lora Text-to-Image": "AtlasCloud ZImage Turbo Lora Text-to-Image",
    "AtlasCloud ZImage Turbo Text-to-Image": "AtlasCloud ZImage Turbo Text-to-Image",
    "AtlasCloud Nano Banana Pro Text-to-Image Ultra": "AtlasCloud Nano Banana Pro Text-to-Image Ultra",
    "AtlasCloud Flux2 Flex Text-to-Image": "AtlasCloud Flux2 Flex Text-to-Image",
    "AtlasCloud Flux Dev Text-to-Image": "AtlasCloud Flux Dev Text-to-Image",
    "AtlasCloud Flux Dev LoRA Text-to-Image": "AtlasCloud Flux Dev LoRA Text-to-Image",
    "AtlasCloud Krea-2 Turbo Text-to-Image": "AtlasCloud Krea-2 Turbo Text-to-Image",
    "AtlasCloud Flux Schnell Text-to-Image": "AtlasCloud Flux Schnell Text-to-Image",
    "AtlasCloud Flux Kontext Dev Edit": "AtlasCloud Flux Kontext Dev Edit",
    "AtlasCloud Flux Kontext Dev LoRA Edit": "AtlasCloud Flux Kontext Dev LoRA Edit",
    "AtlasCloud Video Preview": "AtlasCloud Video Preview",
    "AtlasCloud Image to Base64": "AtlasCloud Image to Base64",
    "AtlasCloud Multi Image to Base64": "AtlasCloud Multi Image to Base64",
    "AtlasCloud Upload Videos to Asset": "AtlasCloud Upload Videos to Asset",
    "AtlasCloud Upload Audio to Asset": "AtlasCloud Upload Audio to Asset",
    "AtlasCloud Multi Image to Seedance Assets": "AtlasCloud Multi Image to Seedance Assets",
    "AtlasCloud Kling V3.0 Pro Text-to-Video": "AtlasCloud Kling V3.0 Pro Text-to-Video",
    "AtlasCloud Kling V3.0 Std Text-to-Video": "AtlasCloud Kling V3.0 Std Text-to-Video",
    "AtlasCloud Kling V3.0 Std Image-to-Video": "AtlasCloud Kling V3.0 Std Image-to-Video",
    "AtlasCloud Kling V3.0 Pro Image-to-Video": "AtlasCloud Kling V3.0 Pro Image-to-Video",
    "AtlasCloud Nano Banana 2 Text-to-Image": "AtlasCloud Nano Banana 2 Text-to-Image",
    "AtlasCloud Nano Banana 2 Text-to-Image Developer": "AtlasCloud Nano Banana 2 Text-to-Image Developer",
    "AtlasCloud Nano Banana 2 Edit": "AtlasCloud Nano Banana 2 Edit",
    "AtlasCloud Nano Banana 2 Edit Developer": "AtlasCloud Nano Banana 2 Edit Developer",
    "AtlasCloud Nano Banana 2 Reference-to-Image": "AtlasCloud Nano Banana 2 Reference-to-Image",
    "AtlasCloud Nano Banana 2 Reference-to-Image Developer": "AtlasCloud Nano Banana 2 Reference-to-Image Developer",
    "AtlasCloud Nano Banana 2 Lite Text-to-Image": "AtlasCloud Nano Banana 2 Lite Text-to-Image",
    "AtlasCloud Nano Banana 2 Lite Text-to-Image Developer": "AtlasCloud Nano Banana 2 Lite Text-to-Image Developer",
    "AtlasCloud Nano Banana 2 Lite Edit": "AtlasCloud Nano Banana 2 Lite Edit",
    "AtlasCloud Nano Banana 2 Lite Edit Developer": "AtlasCloud Nano Banana 2 Lite Edit Developer",
    "AtlasCloud Nano Banana 2 Lite Reference-to-Image": "AtlasCloud Nano Banana 2 Lite Reference-to-Image",
    "AtlasCloud Seedream V5.0 Lite Text-to-Image": "AtlasCloud Seedream V5.0 Lite Text-to-Image",
    "AtlasCloud Seedream V5.0 Lite Sequential Text-to-Image": "AtlasCloud Seedream V5.0 Lite Sequential Text-to-Image",
    "AtlasCloud Seedream V5.0 Lite Edit": "AtlasCloud Seedream V5.0 Lite Edit",
    "AtlasCloud Seedream V5.0 Lite Edit Sequential": "AtlasCloud Seedream V5.0 Lite Edit Sequential",
    "AtlasCloud Vidu Q3 Text-to-Video": "AtlasCloud Vidu Q3 Text-to-Video",
    "AtlasCloud Vidu Q3 Image-to-Video": "AtlasCloud Vidu Q3 Image-to-Video",
    "AtlasCloud Vidu Q3 Image-to-Video (Q3 API)": "AtlasCloud Vidu Q3 Image-to-Video (Q3 API)",
    "AtlasCloud Vidu Q3-Pro Text-to-Video": "AtlasCloud Vidu Q3-Pro Text-to-Video",
    "AtlasCloud Vidu Q3-Pro Image-to-Video": "AtlasCloud Vidu Q3-Pro Image-to-Video",
    "AtlasCloud Vidu Q3-Pro Start-End-to-Video": "AtlasCloud Vidu Q3-Pro Start-End-to-Video",
    "AtlasCloud Vidu Q3-Turbo Text-to-Video": "AtlasCloud Vidu Q3-Turbo Text-to-Video",
    "AtlasCloud Vidu Q3-Turbo Image-to-Video": "AtlasCloud Vidu Q3-Turbo Image-to-Video",
    "AtlasCloud Vidu Q3-Turbo Start-End-to-Video": "AtlasCloud Vidu Q3-Turbo Start-End-to-Video",
    "AtlasCloud WAN2.2 Spicy Image-to-Video": "AtlasCloud WAN2.2 Spicy Image-to-Video",
    "AtlasCloud WAN2.2 Turbo Image-to-Video": "AtlasCloud WAN2.2 Turbo Image-to-Video",
    "AtlasCloud WAN2.2 Turbo Spicy Image-to-Video": "AtlasCloud WAN2.2 Turbo Spicy Image-to-Video",
    "AtlasCloud WAN2.2 Turbo Spicy Image-to-Video LoRA": "AtlasCloud WAN2.2 Turbo Spicy Image-to-Video LoRA",
    "AtlasCloud WAN2.2 Spicy Image-to-Video LoRA": "AtlasCloud WAN2.2 Spicy Image-to-Video LoRA",
    "AtlasCloud VEO3 Text-to-Video": "AtlasCloud VEO3 Text-to-Video",
    "AtlasCloud Imagen4 Text-to-Image": "AtlasCloud Imagen4 Text-to-Image",
    "AtlasCloud Imagen4 Fast Text-to-Image": "AtlasCloud Imagen4 Fast Text-to-Image",
    "AtlasCloud Luma Ray 2 Text-to-Video": "AtlasCloud Luma Ray 2 Text-to-Video",
    "AtlasCloud Luma Ray 2 Image-to-Video": "AtlasCloud Luma Ray 2 Image-to-Video",
    "AtlasCloud Pika V2.2 Text-to-Video": "AtlasCloud Pika V2.2 Text-to-Video",
    "AtlasCloud PixVerse V4.5 Text-to-Video": "AtlasCloud PixVerse V4.5 Text-to-Video",
    "AtlasCloud PixVerse C1 Text-to-Video": "AtlasCloud PixVerse C1 Text-to-Video",
    "AtlasCloud PixVerse C1 Image-to-Video": "AtlasCloud PixVerse C1 Image-to-Video",
    "AtlasCloud PixVerse C1 Reference-to-Video": "AtlasCloud PixVerse C1 Reference-to-Video",
    "AtlasCloud PixVerse V6 Text-to-Video": "AtlasCloud PixVerse V6 Text-to-Video",
    "AtlasCloud PixVerse V6 Image-to-Video": "AtlasCloud PixVerse V6 Image-to-Video",
    "AtlasCloud PixVerse V6 Reference-to-Video": "AtlasCloud PixVerse V6 Reference-to-Video",
    "AtlasCloud PixVerse V6 Video-Extend": "AtlasCloud PixVerse V6 Video-Extend",
    "AtlasCloud PixVerse C1 Start-End-to-Video": "AtlasCloud PixVerse C1 Start-End-to-Video",
    "AtlasCloud PixVerse V6 Start-End-to-Video": "AtlasCloud PixVerse V6 Start-End-to-Video",
    "AtlasCloud Midjourney V8.1 Image-to-Video": "AtlasCloud Midjourney V8.1 Image-to-Video",
    "AtlasCloud Midjourney V8.1 Text-to-Image": "AtlasCloud Midjourney V8.1 Text-to-Image",
    "AtlasCloud Midjourney V8.1 Image-to-Image": "AtlasCloud Midjourney V8.1 Image-to-Image",
    "AtlasCloud Midjourney V8.1 Blend": "AtlasCloud Midjourney V8.1 Blend",
    "AtlasCloud Midjourney V8.1 Remove Background": "AtlasCloud Midjourney V8.1 Remove Background",
    "AtlasCloud Midjourney V8.1 Style Transfer": "AtlasCloud Midjourney V8.1 Style Transfer",
    "AtlasCloud Youchuan V8.1 Image-to-Video": "AtlasCloud Youchuan V8.1 Image-to-Video",
    "AtlasCloud Youchuan V8.1 Text-to-Image": "AtlasCloud Youchuan V8.1 Text-to-Image",
    "AtlasCloud Youchuan V8.1 Image-to-Image": "AtlasCloud Youchuan V8.1 Image-to-Image",
    "AtlasCloud Youchuan V8.1 Blend": "AtlasCloud Youchuan V8.1 Blend",
    "AtlasCloud Youchuan V8.1 Remove Background": "AtlasCloud Youchuan V8.1 Remove Background",
    "AtlasCloud Youchuan V8.1 Style Transfer": "AtlasCloud Youchuan V8.1 Style Transfer",
    "AtlasCloud Kling V3.0 4K Image-to-Video": "AtlasCloud Kling V3.0 4K Image-to-Video",
    "AtlasCloud Kling V3.0 4K Text-to-Video": "AtlasCloud Kling V3.0 4K Text-to-Video",
    "AtlasCloud Kling V3.0 Turbo Image-to-Video": "AtlasCloud Kling V3.0 Turbo Image-to-Video",
    "AtlasCloud Kling V3.0 Turbo Text-to-Video": "AtlasCloud Kling V3.0 Turbo Text-to-Video",
    "AtlasCloud Kling Video O3 4K Image-to-Video": "AtlasCloud Kling Video O3 4K Image-to-Video",
    "AtlasCloud Kling Video O3 4K Text-to-Video": "AtlasCloud Kling Video O3 4K Text-to-Video",
    "AtlasCloud Hailuo 02 T2V Pro": "AtlasCloud Hailuo 02 T2V Pro",
    "AtlasCloud Sora 2 Image-to-Video": "AtlasCloud Sora 2 Image-to-Video",
    "AtlasCloud Kling V2.5 Turbo Pro Text-to-Video": "AtlasCloud Kling V2.5 Turbo Pro Text-to-Video",
    "AtlasCloud Hunyuan Text-to-Video": "AtlasCloud Hunyuan Text-to-Video",
    "AtlasCloud VEO3 Fast Text-to-Video": "AtlasCloud VEO3 Fast Text-to-Video",
    "AtlasCloud VEO3.1 Fast Text-to-Video": "AtlasCloud VEO3.1 Fast Text-to-Video",
    "AtlasCloud VEO3.1 Fast Image-to-Video": "AtlasCloud VEO3.1 Fast Image-to-Video",
    "AtlasCloud Gemini Omni Flash Text-to-Video Developer": "AtlasCloud Gemini Omni Flash Text-to-Video Developer",
    "AtlasCloud Gemini Omni Flash Image-to-Video Developer": "AtlasCloud Gemini Omni Flash Image-to-Video Developer",
    "AtlasCloud Gemini Omni Flash Reference-to-Video Developer": "AtlasCloud Gemini Omni Flash Reference-to-Video Developer",
    "AtlasCloud Gemini Omni Flash Text-to-Video": "AtlasCloud Gemini Omni Flash Text-to-Video",
    "AtlasCloud Gemini Omni Flash Image-to-Video": "AtlasCloud Gemini Omni Flash Image-to-Video",
    "AtlasCloud Gemini Omni Flash Reference-to-Video": "AtlasCloud Gemini Omni Flash Reference-to-Video",
    "AtlasCloud Gemini Omni Flash Video Edit": "AtlasCloud Gemini Omni Flash Video Edit",
    "AtlasCloud VEO3.1 Reference-to-Video": "AtlasCloud VEO3.1 Reference-to-Video",
    "AtlasCloud VEO3.1 Image-to-Video": "AtlasCloud VEO3.1 Image-to-Video",
    "AtlasCloud VEO3 Image-to-Video": "AtlasCloud VEO3 Image-to-Video",
    "AtlasCloud VEO2 Text-to-Video": "AtlasCloud VEO2 Text-to-Video",
    "AtlasCloud VEO2 Image-to-Video": "AtlasCloud VEO2 Image-to-Video",
    "AtlasCloud Luma Ray 2 Flash Text-to-Video": "AtlasCloud Luma Ray 2 Flash Text-to-Video",
    "AtlasCloud Pika V2.0 Turbo Text-to-Video": "AtlasCloud Pika V2.0 Turbo Text-to-Video",
    "AtlasCloud Pika V2.1 Image-to-Video": "AtlasCloud Pika V2.1 Image-to-Video",
    "AtlasCloud PixVerse V4.5 Image-to-Video": "AtlasCloud PixVerse V4.5 Image-to-Video",
    "AtlasCloud Hailuo 02 I2V Pro": "AtlasCloud Hailuo 02 I2V Pro",
    "AtlasCloud Hailuo 02 I2V Standard": "AtlasCloud Hailuo 02 I2V Standard",
    "AtlasCloud Hailuo 02 Standard": "AtlasCloud Hailuo 02 Standard",
    "AtlasCloud Sora 2 Image-to-Video Pro": "AtlasCloud Sora 2 Image-to-Video Pro",
    "AtlasCloud Sora 2 Text-to-Video": "AtlasCloud Sora 2 Text-to-Video",
    "AtlasCloud Kling V2.5 Turbo Pro Image-to-Video": "AtlasCloud Kling V2.5 Turbo Pro Image-to-Video",
    "AtlasCloud Hunyuan Image-to-Video": "AtlasCloud Hunyuan Image-to-Video",
    "AtlasCloud WAN2.5 Image-to-Video": "AtlasCloud WAN2.5 Image-to-Video",
    "AtlasCloud WAN2.2 Image-to-Video 720p": "AtlasCloud WAN2.2 Image-to-Video 720p",
    "AtlasCloud WAN2.2 Image-to-Video 480p": "AtlasCloud WAN2.2 Image-to-Video 480p",
    "AtlasCloud WAN2.2 Animate Mix": "AtlasCloud WAN2.2 Animate Mix",
    "AtlasCloud WAN2.2 Animate Move": "AtlasCloud WAN2.2 Animate Move",
    "AtlasCloud Wan 2.2 Turbo Infinite Image-to-Video": "AtlasCloud Wan 2.2 Turbo Infinite Image-to-Video",
    "AtlasCloud Wan 2.2 Turbo Infinite Image-to-Video LoRA": "AtlasCloud Wan 2.2 Turbo Infinite Image-to-Video LoRA",
    "AtlasCloud Wan 2.2 Turbo Spicy Infinite Image-to-Video": "AtlasCloud Wan 2.2 Turbo Spicy Infinite Image-to-Video",
    "AtlasCloud Wan 2.2 Turbo Spicy Infinite Image-to-Video LoRA": "AtlasCloud Wan 2.2 Turbo Spicy Infinite Image-to-Video LoRA",
    "AtlasCloud WAN2.6 Spicy Image-to-Video": "AtlasCloud WAN2.6 Spicy Image-to-Video",
    "AtlasCloud WAN2.7 Spicy Image-to-Video": "AtlasCloud WAN2.7 Spicy Image-to-Video",
    "AtlasCloud Imagen4 Ultra Text-to-Image": "AtlasCloud Imagen4 Ultra Text-to-Image",
    "AtlasCloud Imagen3 Text-to-Image": "AtlasCloud Imagen3 Text-to-Image",
    "AtlasCloud Imagen3 Fast Text-to-Image": "AtlasCloud Imagen3 Fast Text-to-Image",
    "AtlasCloud Ideogram V3 Quality Text-to-Image": "AtlasCloud Ideogram V3 Quality Text-to-Image",
    "AtlasCloud Ideogram V3 Turbo Text-to-Image": "AtlasCloud Ideogram V3 Turbo Text-to-Image",
    "AtlasCloud Luma Photon Text-to-Image": "AtlasCloud Luma Photon Text-to-Image",
    "AtlasCloud Luma Photon Flash Text-to-Image": "AtlasCloud Luma Photon Flash Text-to-Image",
    "AtlasCloud Recraft V3 Text-to-Image": "AtlasCloud Recraft V3 Text-to-Image",
    "AtlasCloud Qwen Image Edit": "AtlasCloud Qwen Image Edit",
    "AtlasCloud Qwen Image Text-to-Image (AtlasCloud)": "AtlasCloud Qwen Image Text-to-Image (AtlasCloud)",
    "AtlasCloud Qwen Image Edit (Alibaba)": "AtlasCloud Qwen Image Edit (Alibaba)",
    "AtlasCloud Qwen Image Edit Plus (Alibaba)": "AtlasCloud Qwen Image Edit Plus (Alibaba)",
    "AtlasCloud Nano Banana Pro Text-to-Image": "AtlasCloud Nano Banana Pro Text-to-Image",
    "AtlasCloud Nano Banana Pro Text-to-Image Developer": "AtlasCloud Nano Banana Pro Text-to-Image Developer",
    "AtlasCloud Nano Banana Pro Edit": "AtlasCloud Nano Banana Pro Edit",
    "AtlasCloud Nano Banana Pro Edit Ultra": "AtlasCloud Nano Banana Pro Edit Ultra",
    "AtlasCloud Nano Banana Pro Edit Developer": "AtlasCloud Nano Banana Pro Edit Developer",
    "AtlasCloud Nano Banana Text-to-Image": "AtlasCloud Nano Banana Text-to-Image",
    "AtlasCloud Nano Banana Text-to-Image Developer": "AtlasCloud Nano Banana Text-to-Image Developer",
    "AtlasCloud Nano Banana Edit": "AtlasCloud Nano Banana Edit",
    "AtlasCloud Nano Banana Edit Developer": "AtlasCloud Nano Banana Edit Developer",
    "AtlasCloud Qwen Image Edit Plus 20251215": "AtlasCloud Qwen Image Edit Plus 20251215",
    "AtlasCloud Qwen Image Text-to-Image Plus": "AtlasCloud Qwen Image Text-to-Image Plus",
    "AtlasCloud Qwen Image Text-to-Image Max": "AtlasCloud Qwen Image Text-to-Image Max",
    "AtlasCloud GPT Image-1 Text-to-Image": "AtlasCloud GPT Image-1 Text-to-Image",
    "AtlasCloud GPT Image-1 Edit": "AtlasCloud GPT Image-1 Edit",
    "AtlasCloud GPT Image-1 Mini Text-to-Image": "AtlasCloud GPT Image-1 Mini Text-to-Image",
    "AtlasCloud GPT Image-1 Mini Edit": "AtlasCloud GPT Image-1 Mini Edit",
    "AtlasCloud GPT Image-1.5 Text-to-Image": "AtlasCloud GPT Image-1.5 Text-to-Image",
    "AtlasCloud GPT Image-1.5 Edit": "AtlasCloud GPT Image-1.5 Edit",
    "AtlasCloud GPT Image-2 Developer Text-to-Image": "AtlasCloud GPT Image-2 Developer Text-to-Image",
    "AtlasCloud GPT Image-2 Developer Edit": "AtlasCloud GPT Image-2 Developer Edit",
    "AtlasCloud Qwen Image 2.0 Text-to-Image": "AtlasCloud Qwen Image 2.0 Text-to-Image",
    "AtlasCloud Qwen Image 2.0 Edit": "AtlasCloud Qwen Image 2.0 Edit",
    "AtlasCloud Qwen Image 2.0 Pro Text-to-Image": "AtlasCloud Qwen Image 2.0 Pro Text-to-Image",
    "AtlasCloud Qwen Image 2.0 Pro Edit": "AtlasCloud Qwen Image 2.0 Pro Edit",
    "AtlasCloud Seedance V1 Pro Fast Text-to-Video": "AtlasCloud Seedance V1 Pro Fast Text-to-Video",
    "AtlasCloud Seedance V1 Pro Fast Image-to-Video": "AtlasCloud Seedance V1 Pro Fast Image-to-Video",
    "AtlasCloud Seedance V1 Pro Image-to-Video 1080p": "AtlasCloud Seedance V1 Pro Image-to-Video 1080p",
    "AtlasCloud Seedance V1 Pro Image-to-Video 720p": "AtlasCloud Seedance V1 Pro Image-to-Video 720p",
    "AtlasCloud Seedance V1 Pro Image-to-Video 480p": "AtlasCloud Seedance V1 Pro Image-to-Video 480p",
    "AtlasCloud Seedance V1 Lite Image-to-Video 720p": "AtlasCloud Seedance V1 Lite Image-to-Video 720p",
    "AtlasCloud Seedance V1 Lite Image-to-Video 480p": "AtlasCloud Seedance V1 Lite Image-to-Video 480p",
    "AtlasCloud WAN2.5 Text-to-Video Fast": "AtlasCloud WAN2.5 Text-to-Video Fast",
    "AtlasCloud WAN2.5 Image-to-Video Fast": "AtlasCloud WAN2.5 Image-to-Video Fast",
    "AtlasCloud Van-2.5 Text-to-Video": "AtlasCloud Van-2.5 Text-to-Video",
    "AtlasCloud Van-2.5 Image-to-Video": "AtlasCloud Van-2.5 Image-to-Video",
    "AtlasCloud Van-2.6 Text-to-Video": "AtlasCloud Van-2.6 Text-to-Video",
    "AtlasCloud Van-2.6 Image-to-Video": "AtlasCloud Van-2.6 Image-to-Video",
    "AtlasCloud InfiniteTalk Audio-to-Video": "AtlasCloud InfiniteTalk Audio-to-Video",
    "AtlasCloud Vidu Q1 Text-to-Video": "AtlasCloud Vidu Q1 Text-to-Video",
    "AtlasCloud Vidu Q1 Image-to-Video": "AtlasCloud Vidu Q1 Image-to-Video",
    "AtlasCloud Vidu Q1 Start-End-to-Video": "AtlasCloud Vidu Q1 Start-End-to-Video",
    "AtlasCloud Vidu Q1 Reference-to-Video": "AtlasCloud Vidu Q1 Reference-to-Video",
    "AtlasCloud Vidu Q2 Text-to-Video": "AtlasCloud Vidu Q2 Text-to-Video",
    "AtlasCloud Vidu Q2 Reference-to-Video": "AtlasCloud Vidu Q2 Reference-to-Video",
    "AtlasCloud Vidu Q2-Pro Image-to-Video": "AtlasCloud Vidu Q2-Pro Image-to-Video",
    "AtlasCloud Vidu Q2-Pro Start-End-to-Video": "AtlasCloud Vidu Q2-Pro Start-End-to-Video",
    "AtlasCloud Vidu Q2-Pro Reference-to-Video": "AtlasCloud Vidu Q2-Pro Reference-to-Video",
    "AtlasCloud Vidu Q2-Pro-Fast Image-to-Video": "AtlasCloud Vidu Q2-Pro-Fast Image-to-Video",
    "AtlasCloud Vidu Q2-Pro-Fast Start-End-to-Video": "AtlasCloud Vidu Q2-Pro-Fast Start-End-to-Video",
    "AtlasCloud Vidu Q2-Turbo Image-to-Video": "AtlasCloud Vidu Q2-Turbo Image-to-Video",
    "AtlasCloud Vidu Q2-Turbo Start-End-to-Video": "AtlasCloud Vidu Q2-Turbo Start-End-to-Video",
    "AtlasCloud Vidu Reference-to-Video Q1": "AtlasCloud Vidu Reference-to-Video Q1",
    "AtlasCloud Vidu Reference-to-Video 2.0": "AtlasCloud Vidu Reference-to-Video 2.0",
    "AtlasCloud Vidu Q2-Pro-Fast Reference-to-Video": "AtlasCloud Vidu Q2-Pro-Fast Reference-to-Video",
    "AtlasCloud Vidu Q2-Pro-Fast Reference-to-Video (with Audio)": "AtlasCloud Vidu Q2-Pro-Fast Reference-to-Video (with Audio)",
    "AtlasCloud Vidu Start-End-to-Video 2.0": "AtlasCloud Vidu Start-End-to-Video 2.0",
    "AtlasCloud Video Upscaler (Video-to-Video)": "AtlasCloud Video Upscaler (Video-to-Video)",
    "AtlasCloud Veed Fabric 1.0 Image-to-Video": "AtlasCloud Veed Fabric 1.0 Image-to-Video",
    "AtlasCloud Veed Fabric 1.0 Fast Image-to-Video": "AtlasCloud Veed Fabric 1.0 Fast Image-to-Video",
    "AtlasCloud Grok Imagine IQ Text-to-Image": "AtlasCloud Grok Imagine IQ Text-to-Image",
    "AtlasCloud Grok Imagine IQ Edit": "AtlasCloud Grok Imagine IQ Edit",
    "AtlasCloud Grok Imagine Text-to-Image": "AtlasCloud Grok Imagine Text-to-Image",
    "AtlasCloud Grok Imagine Edit": "AtlasCloud Grok Imagine Edit",
    "AtlasCloud Kling V2.0 I2V Master": "AtlasCloud Kling V2.0 I2V Master",
    "AtlasCloud VEO3 Fast Image-to-Video": "AtlasCloud VEO3 Fast Image-to-Video",
    "AtlasCloud Kling V2.1 T2V Master": "AtlasCloud Kling V2.1 T2V Master",
    "AtlasCloud Kling V2.1 I2V Master": "AtlasCloud Kling V2.1 I2V Master",
    "AtlasCloud Kling V2.1 I2V Pro (Start/End Frame)": "AtlasCloud Kling V2.1 I2V Pro (Start/End Frame)",
    "AtlasCloud Kling V2.1 I2V Pro": "AtlasCloud Kling V2.1 I2V Pro",
    "AtlasCloud Kling V2.1 I2V Standard": "AtlasCloud Kling V2.1 I2V Standard",
    "AtlasCloud Kling V1.6 Multi I2V Pro": "AtlasCloud Kling V1.6 Multi I2V Pro",
    "AtlasCloud Kling V1.6 Multi I2V Standard": "AtlasCloud Kling V1.6 Multi I2V Standard",
    "AtlasCloud Kling V1.6 I2V Standard": "AtlasCloud Kling V1.6 I2V Standard",
    "AtlasCloud Kling V1.6 T2V Standard": "AtlasCloud Kling V1.6 T2V Standard",
    "AtlasCloud Kling V1.6 I2V Pro": "AtlasCloud Kling V1.6 I2V Pro",
    "AtlasCloud Kling Effects": "AtlasCloud Kling Effects",
    "AtlasCloud Hailuo 2.3 T2V Standard": "AtlasCloud Hailuo 2.3 T2V Standard",
    "AtlasCloud Hailuo 2.3 I2V Standard": "AtlasCloud Hailuo 2.3 I2V Standard",
    "AtlasCloud Hailuo 2.3 I2V Pro": "AtlasCloud Hailuo 2.3 I2V Pro",
    "AtlasCloud Hailuo 2.3 Fast": "AtlasCloud Hailuo 2.3 Fast",
    "AtlasCloud Hailuo 02 Fast": "AtlasCloud Hailuo 02 Fast",
    "AtlasCloud Hailuo 02 Pro": "AtlasCloud Hailuo 02 Pro",
    "AtlasCloud Hailuo 02 T2V Standard": "AtlasCloud Hailuo 02 T2V Standard",
    "AtlasCloud Seedance V1 Lite T2V 1080p": "AtlasCloud Seedance V1 Lite T2V 1080p",
    "AtlasCloud Seedance V1 Lite T2V 720p": "AtlasCloud Seedance V1 Lite T2V 720p",
    "AtlasCloud Seedance V1 Lite I2V 1080p": "AtlasCloud Seedance V1 Lite I2V 1080p",
    "AtlasCloud Kling V2.0 T2V Master": "AtlasCloud Kling V2.0 T2V Master",
    "AtlasCloud Grok Imagine Video Text-to-Video": "AtlasCloud Grok Imagine Video Text-to-Video",
    "AtlasCloud Grok Imagine Video Image-to-Video": "AtlasCloud Grok Imagine Video Image-to-Video",
    "AtlasCloud Grok Imagine Video v1.5 Image-to-Video": "AtlasCloud Grok Imagine Video v1.5 Image-to-Video",
    "AtlasCloud Grok Imagine Video Reference-to-Video": "AtlasCloud Grok Imagine Video Reference-to-Video",
    "AtlasCloud FLUX.2 Pro Text-to-Image": "AtlasCloud FLUX.2 Pro Text-to-Image",
    "AtlasCloud FLUX.2 Flex Edit": "AtlasCloud FLUX.2 Flex Edit",
    "AtlasCloud FLUX.2 Pro Edit": "AtlasCloud FLUX.2 Pro Edit",
    "AtlasCloud Grok Imagine Video Edit": "AtlasCloud Grok Imagine Video Edit",
    "AtlasCloud Grok Imagine Video Extend": "AtlasCloud Grok Imagine Video Extend",
    "AtlasCloud HiDream O1 1.5 Text-to-Image": "AtlasCloud HiDream O1 1.5 Text-to-Image",
    "AtlasCloud HiDream O1 1.5 Edit": "AtlasCloud HiDream O1 1.5 Edit",
    "AtlasCloud Reve 2.1 Text-to-Image": "AtlasCloud Reve 2.1 Text-to-Image",
    "AtlasCloud Reve 2.1 Edit": "AtlasCloud Reve 2.1 Edit",
    "AtlasCloud Reve 2.1 Remix": "AtlasCloud Reve 2.1 Remix",
    "AtlasCloud Sync Lipsync v3": "AtlasCloud Sync Lipsync v3",
    "AtlasCloud VEED Lipsync": "AtlasCloud VEED Lipsync",
    "AtlasCloud Seedream V5.0 Pro Text-to-Image": "AtlasCloud Seedream V5.0 Pro Text-to-Image",
    "AtlasCloud Seedream V5.0 Pro Edit": "AtlasCloud Seedream V5.0 Pro Edit",
    "AtlasCloud Cosmos 3 Super Text-to-Image": "AtlasCloud Cosmos 3 Super Text-to-Image",
    "AtlasCloud Cosmos 3 Super Image-to-Video": "AtlasCloud Cosmos 3 Super Image-to-Video",
    "AtlasCloud Ideogram V4 Turbo Text-to-Image": "AtlasCloud Ideogram V4 Turbo Text-to-Image",
    "AtlasCloud Ideogram V4 Quality Text-to-Image": "AtlasCloud Ideogram V4 Quality Text-to-Image",
    "AtlasCloud LTX 2.3 Quality Text-to-Video": "AtlasCloud LTX 2.3 Quality Text-to-Video",
    "AtlasCloud LTX 2.3 Quality Image-to-Video": "AtlasCloud LTX 2.3 Quality Image-to-Video",
    "AtlasCloud LTX 2.3 Quality Extend Video": "AtlasCloud LTX 2.3 Quality Extend Video",
}


NODE_CLASS_MAPPINGS["Example"] = LegacyExample
NODE_DISPLAY_NAME_MAPPINGS["Example"] = "Example (Deprecated)"
